// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_ap_fixed_8u_array_ap_fixed_36_16_5_3_0_2u_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer7_out_dout,
        layer7_out_empty_n,
        layer7_out_read,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap,
        layer8_out_din,
        layer8_out_full_n,
        layer8_out_write,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [127:0] layer7_out_dout;
input   layer7_out_empty_n;
output   layer7_out_read;
input  [1:0] layer7_out_num_data_valid;
input  [1:0] layer7_out_fifo_cap;
output  [71:0] layer8_out_din;
input   layer8_out_full_n;
output   layer8_out_write;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer7_out_read;
reg layer8_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer7_out_blk_n;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_state4;
wire   [15:0] data_fu_77_p1;
reg   [15:0] data_reg_166;
reg    ap_block_state1;
reg   [15:0] data_1_reg_171;
reg   [15:0] data_2_reg_176;
reg   [15:0] data_3_reg_181;
reg   [15:0] data_4_reg_186;
reg   [15:0] data_5_reg_191;
reg   [15:0] data_6_reg_196;
reg   [15:0] data_7_reg_201;
reg   [35:0] res_reg_206;
wire    ap_CS_fsm_state3;
reg   [35:0] res_1_reg_211;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_done;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_idle;
wire    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready;
wire   [35:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0;
wire   [35:0] grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1;
reg    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg = 1'b0;
end

myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start),
    .ap_done(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_done),
    .ap_idle(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_idle),
    .ap_ready(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready),
    .data_0_val1(data_reg_166),
    .data_1_val2(data_1_reg_171),
    .data_2_val3(data_2_reg_176),
    .data_3_val4(data_3_reg_181),
    .data_4_val5(data_4_reg_186),
    .data_5_val6(data_5_reg_191),
    .data_6_val7(data_6_reg_196),
    .data_7_val8(data_7_reg_201),
    .ap_return_0(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0),
    .ap_return_1(grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= 1'b1;
        end else if ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready == 1'b1)) begin
            grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        data_1_reg_171 <= {{layer7_out_dout[31:16]}};
        data_2_reg_176 <= {{layer7_out_dout[47:32]}};
        data_3_reg_181 <= {{layer7_out_dout[63:48]}};
        data_4_reg_186 <= {{layer7_out_dout[79:64]}};
        data_5_reg_191 <= {{layer7_out_dout[95:80]}};
        data_6_reg_196 <= {{layer7_out_dout[111:96]}};
        data_7_reg_201 <= {{layer7_out_dout[127:112]}};
        data_reg_166 <= data_fu_77_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        res_1_reg_211 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1;
        res_reg_206 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((layer8_out_full_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((layer8_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((layer7_out_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign data_fu_77_p1 = layer7_out_dout[15:0];

assign grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start = grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg;

assign layer8_out_din = {{res_1_reg_211}, {res_reg_206}};

assign start_out = real_start;

endmodule //myproject_dense_array_ap_fixed_8u_array_ap_fixed_36_16_5_3_0_2u_config8_s
