// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;
output  [36:0] ap_return_0;
output  [36:0] ap_return_1;
output  [36:0] ap_return_2;
output  [36:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
reg   [13:0] trunc_ln42_s_reg_5885;
wire    ap_block_pp0_stage0_11001;
reg   [13:0] trunc_ln42_20_reg_5890;
reg   [14:0] trunc_ln42_35_reg_5895;
reg   [14:0] trunc_ln42_36_reg_5900;
reg   [14:0] trunc_ln42_37_reg_5905;
reg   [13:0] trunc_ln42_39_reg_5910;
reg   [13:0] trunc_ln42_41_reg_5915;
reg   [15:0] trunc_ln42_46_reg_5920;
wire   [15:0] add_ln58_fu_5557_p2;
reg   [15:0] add_ln58_reg_5925;
wire   [15:0] add_ln58_304_fu_5569_p2;
reg   [15:0] add_ln58_304_reg_5930;
wire   [13:0] add_ln58_308_fu_5585_p2;
reg   [13:0] add_ln58_308_reg_5935;
wire   [15:0] add_ln58_311_fu_5591_p2;
reg   [15:0] add_ln58_311_reg_5940;
wire   [15:0] add_ln58_313_fu_5603_p2;
reg   [15:0] add_ln58_313_reg_5945;
wire   [14:0] add_ln58_317_fu_5619_p2;
reg   [14:0] add_ln58_317_reg_5950;
wire   [15:0] add_ln58_320_fu_5625_p2;
reg   [15:0] add_ln58_320_reg_5955;
wire   [15:0] add_ln58_322_fu_5637_p2;
reg   [15:0] add_ln58_322_reg_5960;
wire   [14:0] add_ln58_326_fu_5653_p2;
reg   [14:0] add_ln58_326_reg_5965;
wire   [15:0] add_ln58_329_fu_5659_p2;
reg   [15:0] add_ln58_329_reg_5970;
wire   [15:0] add_ln58_331_fu_5671_p2;
reg   [15:0] add_ln58_331_reg_5975;
wire   [13:0] add_ln58_335_fu_5687_p2;
reg   [13:0] add_ln58_335_reg_5980;
wire  signed [8:0] mul_ln73_259_fu_154_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] mul_ln73_248_fu_155_p1;
wire  signed [15:0] mul_ln73_249_fu_156_p0;
wire  signed [25:0] sext_ln70_129_fu_5019_p1;
wire  signed [9:0] mul_ln73_249_fu_156_p1;
wire  signed [15:0] mul_ln73_244_fu_157_p0;
wire  signed [25:0] sext_ln70_125_fu_4885_p1;
wire   [9:0] mul_ln73_244_fu_157_p1;
wire  signed [15:0] mul_ln73_fu_158_p0;
wire  signed [9:0] mul_ln73_fu_158_p1;
wire  signed [15:0] mul_ln73_256_fu_159_p0;
wire  signed [24:0] sext_ln70_131_fu_5082_p1;
wire  signed [8:0] mul_ln73_256_fu_159_p1;
wire  signed [15:0] mul_ln73_267_fu_160_p0;
wire  signed [25:0] sext_ln70_138_fu_5307_p1;
wire  signed [9:0] mul_ln73_267_fu_160_p1;
wire  signed [15:0] mul_ln73_252_fu_161_p0;
wire  signed [24:0] sext_ln70_128_fu_5013_p1;
wire  signed [8:0] mul_ln73_252_fu_161_p1;
wire  signed [15:0] mul_ln73_247_fu_162_p0;
wire  signed [25:0] sext_ln70_127_fu_4962_p1;
wire  signed [9:0] mul_ln73_247_fu_162_p1;
wire   [7:0] mul_ln73_268_fu_163_p1;
wire   [7:0] mul_ln73_271_fu_164_p1;
wire  signed [15:0] mul_ln73_270_fu_165_p0;
wire  signed [25:0] sext_ln70_144_fu_5485_p1;
wire   [9:0] mul_ln73_270_fu_165_p1;
wire   [8:0] mul_ln73_263_fu_166_p1;
wire   [7:0] mul_ln73_262_fu_167_p1;
wire  signed [7:0] mul_ln73_243_fu_169_p1;
wire  signed [15:0] mul_ln73_245_fu_171_p0;
wire   [9:0] mul_ln73_245_fu_171_p1;
wire   [7:0] mul_ln73_266_fu_172_p1;
wire  signed [9:0] mul_ln73_254_fu_173_p1;
wire  signed [15:0] mul_ln73_257_fu_174_p0;
wire  signed [25:0] sext_ln70_133_fu_5150_p1;
wire   [9:0] mul_ln73_257_fu_174_p1;
wire  signed [15:0] mul_ln73_253_fu_175_p0;
wire   [8:0] mul_ln73_253_fu_175_p1;
wire  signed [6:0] mul_ln73_261_fu_176_p1;
wire  signed [15:0] mul_ln73_251_fu_178_p0;
wire   [8:0] mul_ln73_251_fu_178_p1;
wire  signed [15:0] mul_ln73_265_fu_179_p0;
wire   [9:0] mul_ln73_265_fu_179_p1;
wire  signed [15:0] mul_ln73_272_fu_180_p0;
wire  signed [9:0] mul_ln73_272_fu_180_p1;
wire  signed [15:0] mul_ln73_260_fu_181_p0;
wire   [9:0] mul_ln73_260_fu_181_p1;
wire  signed [15:0] mul_ln73_250_fu_183_p0;
wire  signed [9:0] mul_ln73_250_fu_183_p1;
wire  signed [6:0] mul_ln73_269_fu_184_p1;
wire  signed [15:0] mul_ln73_258_fu_185_p0;
wire  signed [9:0] mul_ln73_258_fu_185_p1;
wire  signed [15:0] mul_ln73_246_fu_186_p0;
wire   [9:0] mul_ln73_246_fu_186_p1;
wire  signed [8:0] mul_ln73_264_fu_187_p1;
wire  signed [15:0] mul_ln73_255_fu_189_p0;
wire  signed [8:0] mul_ln73_255_fu_189_p1;
wire  signed [15:0] sext_ln70_fu_4876_p0;
wire  signed [15:0] sext_ln70_124_fu_4880_p0;
wire  signed [15:0] sext_ln70_125_fu_4885_p0;
wire   [25:0] mul_ln73_fu_158_p2;
wire   [23:0] mul_ln73_243_fu_169_p2;
wire   [25:0] mul_ln73_244_fu_157_p2;
wire  signed [15:0] tmp_fu_4921_p1;
wire   [18:0] tmp_fu_4921_p3;
wire  signed [20:0] sext_ln73_79_fu_4929_p1;
wire  signed [20:0] sext_ln70_fu_4876_p1;
wire   [20:0] add_ln73_fu_4933_p2;
wire   [10:0] trunc_ln42_16_fu_4939_p4;
wire  signed [15:0] sext_ln70_126_fu_4957_p0;
wire  signed [15:0] sext_ln70_127_fu_4962_p0;
wire   [25:0] mul_ln73_245_fu_171_p2;
wire   [25:0] mul_ln73_246_fu_186_p2;
wire   [25:0] mul_ln73_247_fu_162_p2;
wire   [23:0] mul_ln73_248_fu_155_p2;
wire  signed [15:0] sext_ln70_128_fu_5013_p0;
wire  signed [15:0] sext_ln70_129_fu_5019_p0;
wire   [25:0] mul_ln73_249_fu_156_p2;
wire   [25:0] mul_ln73_250_fu_183_p2;
wire   [24:0] mul_ln73_251_fu_178_p2;
wire   [14:0] trunc_ln42_23_fu_5045_p4;
wire   [24:0] mul_ln73_252_fu_161_p2;
wire   [14:0] trunc_ln42_24_fu_5059_p4;
wire  signed [15:0] sext_ln70_130_fu_5077_p0;
wire  signed [15:0] sext_ln70_131_fu_5082_p0;
wire   [24:0] mul_ln73_253_fu_175_p2;
wire   [14:0] trunc_ln42_25_fu_5089_p4;
wire   [25:0] mul_ln73_254_fu_173_p2;
wire   [24:0] mul_ln73_255_fu_189_p2;
wire   [14:0] trunc_ln42_27_fu_5113_p4;
wire   [24:0] mul_ln73_256_fu_159_p2;
wire   [14:0] trunc_ln42_28_fu_5127_p4;
wire  signed [15:0] sext_ln70_132_fu_5145_p0;
wire  signed [15:0] sext_ln70_133_fu_5150_p0;
wire   [25:0] mul_ln73_257_fu_174_p2;
wire   [25:0] mul_ln73_258_fu_185_p2;
wire   [24:0] mul_ln73_259_fu_154_p2;
wire   [14:0] trunc_ln42_31_fu_5177_p4;
wire   [25:0] mul_ln73_260_fu_181_p2;
wire  signed [15:0] sext_ln70_134_fu_5205_p0;
wire  signed [15:0] sext_ln70_135_fu_5210_p0;
wire  signed [15:0] sext_ln70_136_fu_5215_p0;
wire   [22:0] mul_ln73_261_fu_176_p2;
wire   [12:0] trunc_ln42_33_fu_5220_p4;
wire   [23:0] mul_ln73_262_fu_167_p2;
wire   [13:0] trunc_ln42_34_fu_5234_p4;
wire  signed [15:0] tmp_90_fu_5248_p1;
wire   [23:0] tmp_90_fu_5248_p3;
wire  signed [15:0] tmp_91_fu_5260_p1;
wire   [20:0] tmp_91_fu_5260_p3;
wire  signed [24:0] sext_ln73_80_fu_5256_p1;
wire  signed [24:0] sext_ln73_81_fu_5268_p1;
wire   [24:0] sub_ln73_fu_5272_p2;
wire   [24:0] mul_ln73_263_fu_166_p2;
wire  signed [15:0] sext_ln70_137_fu_5302_p0;
wire  signed [15:0] sext_ln70_138_fu_5307_p0;
wire  signed [15:0] sext_ln70_139_fu_5313_p0;
wire   [24:0] mul_ln73_264_fu_187_p2;
wire   [25:0] mul_ln73_265_fu_179_p2;
wire   [23:0] mul_ln73_266_fu_172_p2;
wire   [25:0] mul_ln73_267_fu_160_p2;
wire  signed [15:0] sext_ln70_140_fu_5362_p0;
wire  signed [15:0] sext_ln70_141_fu_5367_p0;
wire  signed [15:0] sext_ln70_142_fu_5371_p0;
wire   [23:0] mul_ln73_268_fu_163_p2;
wire  signed [15:0] tmp_92_fu_5386_p1;
wire   [18:0] tmp_92_fu_5386_p3;
wire  signed [20:0] sext_ln73_82_fu_5394_p1;
wire  signed [20:0] sext_ln70_141_fu_5367_p1;
wire   [20:0] add_ln73_15_fu_5398_p2;
wire   [10:0] trunc_ln42_42_fu_5404_p4;
wire  signed [15:0] tmp_93_fu_5418_p1;
wire   [19:0] tmp_93_fu_5418_p3;
wire  signed [15:0] tmp_94_fu_5430_p1;
wire   [17:0] tmp_94_fu_5430_p3;
wire  signed [20:0] sext_ln73_84_fu_5438_p1;
wire  signed [20:0] sext_ln73_83_fu_5426_p1;
wire   [20:0] sub_ln73_39_fu_5442_p2;
wire   [10:0] trunc_ln42_43_fu_5448_p4;
wire   [22:0] mul_ln73_269_fu_184_p2;
wire   [12:0] trunc_ln42_44_fu_5462_p4;
wire  signed [15:0] sext_ln70_143_fu_5480_p0;
wire  signed [15:0] sext_ln70_144_fu_5485_p0;
wire  signed [15:0] tmp_95_fu_5491_p1;
wire   [17:0] tmp_95_fu_5491_p3;
wire  signed [18:0] sext_ln73_85_fu_5499_p1;
wire   [18:0] sub_ln73_40_fu_5503_p2;
wire   [8:0] trunc_ln42_45_fu_5509_p4;
wire   [25:0] mul_ln73_270_fu_165_p2;
wire   [23:0] mul_ln73_271_fu_164_p2;
wire   [13:0] trunc_ln42_47_fu_5533_p4;
wire   [25:0] mul_ln73_272_fu_180_p2;
wire   [15:0] trunc_ln_fu_4891_p4;
wire   [15:0] trunc_ln42_17_fu_4969_p4;
wire   [15:0] trunc_ln42_29_fu_5157_p4;
wire  signed [15:0] sext_ln42_119_fu_5099_p1;
wire   [15:0] add_ln58_303_fu_5563_p2;
wire   [15:0] trunc_ln42_21_fu_5025_p4;
wire  signed [9:0] sext_ln73_7_fu_5519_p1;
wire   [9:0] add_ln58_307_fu_5575_p2;
wire  signed [13:0] sext_ln58_fu_5581_p1;
wire  signed [13:0] sext_ln73_fu_5230_p1;
wire   [15:0] trunc_ln42_18_fu_4979_p4;
wire   [15:0] trunc_ln42_22_fu_5035_p4;
wire   [15:0] trunc_ln42_30_fu_5167_p4;
wire   [15:0] trunc_ln42_38_fu_5328_p4;
wire   [15:0] add_ln58_312_fu_5597_p2;
wire   [15:0] trunc_ln42_26_fu_5103_p4;
wire  signed [11:0] sext_ln73_5_fu_5414_p1;
wire   [11:0] add_ln58_316_fu_5609_p2;
wire  signed [14:0] sext_ln58_59_fu_5615_p1;
wire  signed [14:0] sext_ln73_4_fu_5244_p1;
wire   [15:0] trunc_ln42_15_fu_4911_p4;
wire   [15:0] trunc_ln42_19_fu_4989_p4;
wire  signed [15:0] sext_ln42_120_fu_5123_p1;
wire  signed [15:0] sext_ln42_122_fu_5187_p1;
wire   [15:0] add_ln58_321_fu_5631_p2;
wire  signed [15:0] sext_ln42_117_fu_5055_p1;
wire  signed [11:0] sext_ln73_6_fu_5458_p1;
wire   [11:0] add_ln58_325_fu_5643_p2;
wire  signed [14:0] sext_ln58_61_fu_5649_p1;
wire  signed [14:0] sext_ln73_8_fu_5543_p1;
wire   [15:0] trunc_ln42_32_fu_5191_p4;
wire   [15:0] trunc_ln42_40_fu_5348_p4;
wire  signed [15:0] sext_ln42_118_fu_5069_p1;
wire  signed [15:0] sext_ln42_121_fu_5137_p1;
wire   [15:0] add_ln58_330_fu_5665_p2;
wire   [15:0] trunc_ln42_48_fu_5547_p4;
wire  signed [11:0] p_cast32_cast_fu_4949_p1;
wire   [11:0] add_ln58_334_fu_5677_p2;
wire  signed [13:0] sext_ln58_63_fu_5683_p1;
wire  signed [13:0] p_cast49_cast_fu_5472_p1;
wire  signed [15:0] sext_ln42_125_fu_5705_p1;
wire  signed [15:0] sext_ln42_127_fu_5711_p1;
wire  signed [15:0] sext_ln58_58_fu_5724_p1;
wire   [15:0] add_ln58_306_fu_5718_p2;
wire   [15:0] add_ln58_309_fu_5727_p2;
wire   [15:0] add_ln58_305_fu_5714_p2;
wire  signed [15:0] sext_ln42_fu_5693_p1;
wire  signed [15:0] sext_ln58_60_fu_5748_p1;
wire   [15:0] add_ln58_315_fu_5743_p2;
wire   [15:0] add_ln58_318_fu_5751_p2;
wire   [15:0] add_ln58_314_fu_5739_p2;
wire  signed [15:0] sext_ln42_123_fu_5699_p1;
wire  signed [15:0] sext_ln42_126_fu_5708_p1;
wire  signed [15:0] sext_ln58_62_fu_5773_p1;
wire   [15:0] add_ln58_324_fu_5767_p2;
wire   [15:0] add_ln58_327_fu_5776_p2;
wire   [15:0] add_ln58_323_fu_5763_p2;
wire  signed [15:0] sext_ln42_124_fu_5702_p1;
wire  signed [15:0] sext_ln42_116_fu_5696_p1;
wire  signed [15:0] sext_ln58_64_fu_5798_p1;
wire   [15:0] add_ln58_333_fu_5792_p2;
wire   [15:0] add_ln58_336_fu_5801_p2;
wire   [15:0] add_ln58_332_fu_5788_p2;
wire   [15:0] x_fu_5733_p2;
wire   [25:0] shl_ln_fu_5813_p3;
wire   [15:0] x_11_fu_5757_p2;
wire   [25:0] shl_ln111_9_fu_5825_p3;
wire   [15:0] x_12_fu_5782_p2;
wire   [25:0] shl_ln111_s_fu_5837_p3;
wire   [15:0] x_13_fu_5807_p2;
wire   [25:0] shl_ln111_1_fu_5849_p3;
wire  signed [36:0] sext_ln110_fu_5821_p1;
wire  signed [36:0] sext_ln110_7_fu_5833_p1;
wire  signed [36:0] sext_ln110_8_fu_5845_p1;
wire  signed [36:0] sext_ln68_fu_5857_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U12(
    .din0(sext_ln70_132_fu_5145_p0),
    .din1(mul_ln73_259_fu_154_p1),
    .dout(mul_ln73_259_fu_154_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U13(
    .din0(sext_ln70_126_fu_4957_p0),
    .din1(mul_ln73_248_fu_155_p1),
    .dout(mul_ln73_248_fu_155_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U14(
    .din0(mul_ln73_249_fu_156_p0),
    .din1(mul_ln73_249_fu_156_p1),
    .dout(mul_ln73_249_fu_156_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U15(
    .din0(mul_ln73_244_fu_157_p0),
    .din1(mul_ln73_244_fu_157_p1),
    .dout(mul_ln73_244_fu_157_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U16(
    .din0(mul_ln73_fu_158_p0),
    .din1(mul_ln73_fu_158_p1),
    .dout(mul_ln73_fu_158_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U17(
    .din0(mul_ln73_256_fu_159_p0),
    .din1(mul_ln73_256_fu_159_p1),
    .dout(mul_ln73_256_fu_159_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U18(
    .din0(mul_ln73_267_fu_160_p0),
    .din1(mul_ln73_267_fu_160_p1),
    .dout(mul_ln73_267_fu_160_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U19(
    .din0(mul_ln73_252_fu_161_p0),
    .din1(mul_ln73_252_fu_161_p1),
    .dout(mul_ln73_252_fu_161_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U20(
    .din0(mul_ln73_247_fu_162_p0),
    .din1(mul_ln73_247_fu_162_p1),
    .dout(mul_ln73_247_fu_162_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U21(
    .din0(sext_ln70_142_fu_5371_p0),
    .din1(mul_ln73_268_fu_163_p1),
    .dout(mul_ln73_268_fu_163_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U22(
    .din0(sext_ln70_143_fu_5480_p0),
    .din1(mul_ln73_271_fu_164_p1),
    .dout(mul_ln73_271_fu_164_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U23(
    .din0(mul_ln73_270_fu_165_p0),
    .din1(mul_ln73_270_fu_165_p1),
    .dout(mul_ln73_270_fu_165_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U24(
    .din0(sext_ln70_134_fu_5205_p0),
    .din1(mul_ln73_263_fu_166_p1),
    .dout(mul_ln73_263_fu_166_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U25(
    .din0(sext_ln70_135_fu_5210_p0),
    .din1(mul_ln73_262_fu_167_p1),
    .dout(mul_ln73_262_fu_167_p2)
);

myproject_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U26(
    .din0(sext_ln70_124_fu_4880_p0),
    .din1(mul_ln73_243_fu_169_p1),
    .dout(mul_ln73_243_fu_169_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U27(
    .din0(mul_ln73_245_fu_171_p0),
    .din1(mul_ln73_245_fu_171_p1),
    .dout(mul_ln73_245_fu_171_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U28(
    .din0(sext_ln70_137_fu_5302_p0),
    .din1(mul_ln73_266_fu_172_p1),
    .dout(mul_ln73_266_fu_172_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U29(
    .din0(sext_ln70_130_fu_5077_p0),
    .din1(mul_ln73_254_fu_173_p1),
    .dout(mul_ln73_254_fu_173_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U30(
    .din0(mul_ln73_257_fu_174_p0),
    .din1(mul_ln73_257_fu_174_p1),
    .dout(mul_ln73_257_fu_174_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U31(
    .din0(mul_ln73_253_fu_175_p0),
    .din1(mul_ln73_253_fu_175_p1),
    .dout(mul_ln73_253_fu_175_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U32(
    .din0(sext_ln70_136_fu_5215_p0),
    .din1(mul_ln73_261_fu_176_p1),
    .dout(mul_ln73_261_fu_176_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U33(
    .din0(mul_ln73_251_fu_178_p0),
    .din1(mul_ln73_251_fu_178_p1),
    .dout(mul_ln73_251_fu_178_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U34(
    .din0(mul_ln73_265_fu_179_p0),
    .din1(mul_ln73_265_fu_179_p1),
    .dout(mul_ln73_265_fu_179_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U35(
    .din0(mul_ln73_272_fu_180_p0),
    .din1(mul_ln73_272_fu_180_p1),
    .dout(mul_ln73_272_fu_180_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U36(
    .din0(mul_ln73_260_fu_181_p0),
    .din1(mul_ln73_260_fu_181_p1),
    .dout(mul_ln73_260_fu_181_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U37(
    .din0(mul_ln73_250_fu_183_p0),
    .din1(mul_ln73_250_fu_183_p1),
    .dout(mul_ln73_250_fu_183_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U38(
    .din0(sext_ln70_140_fu_5362_p0),
    .din1(mul_ln73_269_fu_184_p1),
    .dout(mul_ln73_269_fu_184_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U39(
    .din0(mul_ln73_258_fu_185_p0),
    .din1(mul_ln73_258_fu_185_p1),
    .dout(mul_ln73_258_fu_185_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U40(
    .din0(mul_ln73_246_fu_186_p0),
    .din1(mul_ln73_246_fu_186_p1),
    .dout(mul_ln73_246_fu_186_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U41(
    .din0(sext_ln70_139_fu_5313_p0),
    .din1(mul_ln73_264_fu_187_p1),
    .dout(mul_ln73_264_fu_187_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U42(
    .din0(mul_ln73_255_fu_189_p0),
    .din1(mul_ln73_255_fu_189_p1),
    .dout(mul_ln73_255_fu_189_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_304_reg_5930 <= add_ln58_304_fu_5569_p2;
        add_ln58_308_reg_5935 <= add_ln58_308_fu_5585_p2;
        add_ln58_311_reg_5940 <= add_ln58_311_fu_5591_p2;
        add_ln58_313_reg_5945 <= add_ln58_313_fu_5603_p2;
        add_ln58_317_reg_5950 <= add_ln58_317_fu_5619_p2;
        add_ln58_320_reg_5955 <= add_ln58_320_fu_5625_p2;
        add_ln58_322_reg_5960 <= add_ln58_322_fu_5637_p2;
        add_ln58_326_reg_5965 <= add_ln58_326_fu_5653_p2;
        add_ln58_329_reg_5970 <= add_ln58_329_fu_5659_p2;
        add_ln58_331_reg_5975 <= add_ln58_331_fu_5671_p2;
        add_ln58_335_reg_5980 <= add_ln58_335_fu_5687_p2;
        add_ln58_reg_5925 <= add_ln58_fu_5557_p2;
        trunc_ln42_20_reg_5890 <= {{mul_ln73_248_fu_155_p2[23:10]}};
        trunc_ln42_35_reg_5895 <= {{sub_ln73_fu_5272_p2[24:10]}};
        trunc_ln42_36_reg_5900 <= {{mul_ln73_263_fu_166_p2[24:10]}};
        trunc_ln42_37_reg_5905 <= {{mul_ln73_264_fu_187_p2[24:10]}};
        trunc_ln42_39_reg_5910 <= {{mul_ln73_266_fu_172_p2[23:10]}};
        trunc_ln42_41_reg_5915 <= {{mul_ln73_268_fu_163_p2[23:10]}};
        trunc_ln42_46_reg_5920 <= {{mul_ln73_270_fu_165_p2[25:10]}};
        trunc_ln42_s_reg_5885 <= {{mul_ln73_243_fu_169_p2[23:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_303_fu_5563_p2 = ($signed(trunc_ln42_29_fu_5157_p4) + $signed(sext_ln42_119_fu_5099_p1));

assign add_ln58_304_fu_5569_p2 = (add_ln58_303_fu_5563_p2 + trunc_ln42_21_fu_5025_p4);

assign add_ln58_305_fu_5714_p2 = (add_ln58_304_reg_5930 + add_ln58_reg_5925);

assign add_ln58_306_fu_5718_p2 = ($signed(sext_ln42_125_fu_5705_p1) + $signed(sext_ln42_127_fu_5711_p1));

assign add_ln58_307_fu_5575_p2 = ($signed(sext_ln73_7_fu_5519_p1) + $signed(10'd1020));

assign add_ln58_308_fu_5585_p2 = ($signed(sext_ln58_fu_5581_p1) + $signed(sext_ln73_fu_5230_p1));

assign add_ln58_309_fu_5727_p2 = ($signed(sext_ln58_58_fu_5724_p1) + $signed(add_ln58_306_fu_5718_p2));

assign add_ln58_311_fu_5591_p2 = (trunc_ln42_18_fu_4979_p4 + trunc_ln42_22_fu_5035_p4);

assign add_ln58_312_fu_5597_p2 = (trunc_ln42_30_fu_5167_p4 + trunc_ln42_38_fu_5328_p4);

assign add_ln58_313_fu_5603_p2 = (add_ln58_312_fu_5597_p2 + trunc_ln42_26_fu_5103_p4);

assign add_ln58_314_fu_5739_p2 = (add_ln58_313_reg_5945 + add_ln58_311_reg_5940);

assign add_ln58_315_fu_5743_p2 = ($signed(trunc_ln42_46_reg_5920) + $signed(sext_ln42_fu_5693_p1));

assign add_ln58_316_fu_5609_p2 = ($signed(sext_ln73_5_fu_5414_p1) + $signed(12'd4093));

assign add_ln58_317_fu_5619_p2 = ($signed(sext_ln58_59_fu_5615_p1) + $signed(sext_ln73_4_fu_5244_p1));

assign add_ln58_318_fu_5751_p2 = ($signed(sext_ln58_60_fu_5748_p1) + $signed(add_ln58_315_fu_5743_p2));

assign add_ln58_320_fu_5625_p2 = (trunc_ln42_15_fu_4911_p4 + trunc_ln42_19_fu_4989_p4);

assign add_ln58_321_fu_5631_p2 = ($signed(sext_ln42_120_fu_5123_p1) + $signed(sext_ln42_122_fu_5187_p1));

assign add_ln58_322_fu_5637_p2 = ($signed(add_ln58_321_fu_5631_p2) + $signed(sext_ln42_117_fu_5055_p1));

assign add_ln58_323_fu_5763_p2 = (add_ln58_322_reg_5960 + add_ln58_320_reg_5955);

assign add_ln58_324_fu_5767_p2 = ($signed(sext_ln42_123_fu_5699_p1) + $signed(sext_ln42_126_fu_5708_p1));

assign add_ln58_325_fu_5643_p2 = ($signed(sext_ln73_6_fu_5458_p1) + $signed(12'd4091));

assign add_ln58_326_fu_5653_p2 = ($signed(sext_ln58_61_fu_5649_p1) + $signed(sext_ln73_8_fu_5543_p1));

assign add_ln58_327_fu_5776_p2 = ($signed(sext_ln58_62_fu_5773_p1) + $signed(add_ln58_324_fu_5767_p2));

assign add_ln58_329_fu_5659_p2 = (trunc_ln42_32_fu_5191_p4 + trunc_ln42_40_fu_5348_p4);

assign add_ln58_330_fu_5665_p2 = ($signed(sext_ln42_118_fu_5069_p1) + $signed(sext_ln42_121_fu_5137_p1));

assign add_ln58_331_fu_5671_p2 = (add_ln58_330_fu_5665_p2 + trunc_ln42_48_fu_5547_p4);

assign add_ln58_332_fu_5788_p2 = (add_ln58_331_reg_5975 + add_ln58_329_reg_5970);

assign add_ln58_333_fu_5792_p2 = ($signed(sext_ln42_124_fu_5702_p1) + $signed(sext_ln42_116_fu_5696_p1));

assign add_ln58_334_fu_5677_p2 = ($signed(p_cast32_cast_fu_4949_p1) + $signed(12'd6));

assign add_ln58_335_fu_5687_p2 = ($signed(sext_ln58_63_fu_5683_p1) + $signed(p_cast49_cast_fu_5472_p1));

assign add_ln58_336_fu_5801_p2 = ($signed(sext_ln58_64_fu_5798_p1) + $signed(add_ln58_333_fu_5792_p2));

assign add_ln58_fu_5557_p2 = (trunc_ln_fu_4891_p4 + trunc_ln42_17_fu_4969_p4);

assign add_ln73_15_fu_5398_p2 = ($signed(sext_ln73_82_fu_5394_p1) + $signed(sext_ln70_141_fu_5367_p1));

assign add_ln73_fu_4933_p2 = ($signed(sext_ln73_79_fu_4929_p1) + $signed(sext_ln70_fu_4876_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln110_fu_5821_p1;

assign ap_return_1 = sext_ln110_7_fu_5833_p1;

assign ap_return_2 = sext_ln110_8_fu_5845_p1;

assign ap_return_3 = sext_ln68_fu_5857_p1;

assign mul_ln73_243_fu_169_p1 = 24'd16777129;

assign mul_ln73_244_fu_157_p0 = sext_ln70_125_fu_4885_p1;

assign mul_ln73_244_fu_157_p1 = 26'd291;

assign mul_ln73_245_fu_171_p0 = sext_ln70_127_fu_4962_p1;

assign mul_ln73_245_fu_171_p1 = 26'd344;

assign mul_ln73_246_fu_186_p0 = sext_ln70_127_fu_4962_p1;

assign mul_ln73_246_fu_186_p1 = 26'd266;

assign mul_ln73_247_fu_162_p0 = sext_ln70_127_fu_4962_p1;

assign mul_ln73_247_fu_162_p1 = 26'd67108599;

assign mul_ln73_248_fu_155_p1 = 24'd99;

assign mul_ln73_249_fu_156_p0 = sext_ln70_129_fu_5019_p1;

assign mul_ln73_249_fu_156_p1 = 26'd67108572;

assign mul_ln73_250_fu_183_p0 = sext_ln70_129_fu_5019_p1;

assign mul_ln73_250_fu_183_p1 = 26'd67108574;

assign mul_ln73_251_fu_178_p0 = sext_ln70_128_fu_5013_p1;

assign mul_ln73_251_fu_178_p1 = 25'd215;

assign mul_ln73_252_fu_161_p0 = sext_ln70_128_fu_5013_p1;

assign mul_ln73_252_fu_161_p1 = 25'd33554244;

assign mul_ln73_253_fu_175_p0 = sext_ln70_131_fu_5082_p1;

assign mul_ln73_253_fu_175_p1 = 25'd227;

assign mul_ln73_254_fu_173_p1 = 26'd67108495;

assign mul_ln73_255_fu_189_p0 = sext_ln70_131_fu_5082_p1;

assign mul_ln73_255_fu_189_p1 = 25'd33554258;

assign mul_ln73_256_fu_159_p0 = sext_ln70_131_fu_5082_p1;

assign mul_ln73_256_fu_159_p1 = 25'd33554189;

assign mul_ln73_257_fu_174_p0 = sext_ln70_133_fu_5150_p1;

assign mul_ln73_257_fu_174_p1 = 26'd293;

assign mul_ln73_258_fu_185_p0 = sext_ln70_133_fu_5150_p1;

assign mul_ln73_258_fu_185_p1 = 26'd67108596;

assign mul_ln73_259_fu_154_p1 = 25'd33554253;

assign mul_ln73_260_fu_181_p0 = sext_ln70_133_fu_5150_p1;

assign mul_ln73_260_fu_181_p1 = 26'd348;

assign mul_ln73_261_fu_176_p1 = 23'd8388562;

assign mul_ln73_262_fu_167_p1 = 24'd105;

assign mul_ln73_263_fu_166_p1 = 25'd193;

assign mul_ln73_264_fu_187_p1 = 25'd33554213;

assign mul_ln73_265_fu_179_p0 = sext_ln70_138_fu_5307_p1;

assign mul_ln73_265_fu_179_p1 = 26'd304;

assign mul_ln73_266_fu_172_p1 = 24'd85;

assign mul_ln73_267_fu_160_p0 = sext_ln70_138_fu_5307_p1;

assign mul_ln73_267_fu_160_p1 = 26'd67108495;

assign mul_ln73_268_fu_163_p1 = 24'd79;

assign mul_ln73_269_fu_184_p1 = 23'd8388557;

assign mul_ln73_270_fu_165_p0 = sext_ln70_144_fu_5485_p1;

assign mul_ln73_270_fu_165_p1 = 26'd331;

assign mul_ln73_271_fu_164_p1 = 24'd74;

assign mul_ln73_272_fu_180_p0 = sext_ln70_144_fu_5485_p1;

assign mul_ln73_272_fu_180_p1 = 26'd67108500;

assign mul_ln73_fu_158_p0 = sext_ln70_125_fu_4885_p1;

assign mul_ln73_fu_158_p1 = 26'd67108508;

assign p_cast32_cast_fu_4949_p1 = $signed(trunc_ln42_16_fu_4939_p4);

assign p_cast49_cast_fu_5472_p1 = $signed(trunc_ln42_44_fu_5462_p4);

assign sext_ln110_7_fu_5833_p1 = $signed(shl_ln111_9_fu_5825_p3);

assign sext_ln110_8_fu_5845_p1 = $signed(shl_ln111_s_fu_5837_p3);

assign sext_ln110_fu_5821_p1 = $signed(shl_ln_fu_5813_p3);

assign sext_ln42_116_fu_5696_p1 = $signed(trunc_ln42_20_reg_5890);

assign sext_ln42_117_fu_5055_p1 = $signed(trunc_ln42_23_fu_5045_p4);

assign sext_ln42_118_fu_5069_p1 = $signed(trunc_ln42_24_fu_5059_p4);

assign sext_ln42_119_fu_5099_p1 = $signed(trunc_ln42_25_fu_5089_p4);

assign sext_ln42_120_fu_5123_p1 = $signed(trunc_ln42_27_fu_5113_p4);

assign sext_ln42_121_fu_5137_p1 = $signed(trunc_ln42_28_fu_5127_p4);

assign sext_ln42_122_fu_5187_p1 = $signed(trunc_ln42_31_fu_5177_p4);

assign sext_ln42_123_fu_5699_p1 = $signed(trunc_ln42_35_reg_5895);

assign sext_ln42_124_fu_5702_p1 = $signed(trunc_ln42_36_reg_5900);

assign sext_ln42_125_fu_5705_p1 = $signed(trunc_ln42_37_reg_5905);

assign sext_ln42_126_fu_5708_p1 = $signed(trunc_ln42_39_reg_5910);

assign sext_ln42_127_fu_5711_p1 = $signed(trunc_ln42_41_reg_5915);

assign sext_ln42_fu_5693_p1 = $signed(trunc_ln42_s_reg_5885);

assign sext_ln58_58_fu_5724_p1 = $signed(add_ln58_308_reg_5935);

assign sext_ln58_59_fu_5615_p1 = $signed(add_ln58_316_fu_5609_p2);

assign sext_ln58_60_fu_5748_p1 = $signed(add_ln58_317_reg_5950);

assign sext_ln58_61_fu_5649_p1 = $signed(add_ln58_325_fu_5643_p2);

assign sext_ln58_62_fu_5773_p1 = $signed(add_ln58_326_reg_5965);

assign sext_ln58_63_fu_5683_p1 = $signed(add_ln58_334_fu_5677_p2);

assign sext_ln58_64_fu_5798_p1 = $signed(add_ln58_335_reg_5980);

assign sext_ln58_fu_5581_p1 = $signed(add_ln58_307_fu_5575_p2);

assign sext_ln68_fu_5857_p1 = $signed(shl_ln111_1_fu_5849_p3);

assign sext_ln70_124_fu_4880_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign sext_ln70_125_fu_4885_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign sext_ln70_125_fu_4885_p1 = sext_ln70_125_fu_4885_p0;

assign sext_ln70_126_fu_4957_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign sext_ln70_127_fu_4962_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_7;

assign sext_ln70_127_fu_4962_p1 = sext_ln70_127_fu_4962_p0;

assign sext_ln70_128_fu_5013_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign sext_ln70_128_fu_5013_p1 = sext_ln70_128_fu_5013_p0;

assign sext_ln70_129_fu_5019_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_6;

assign sext_ln70_129_fu_5019_p1 = sext_ln70_129_fu_5019_p0;

assign sext_ln70_130_fu_5077_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;

assign sext_ln70_131_fu_5082_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_5;

assign sext_ln70_131_fu_5082_p1 = sext_ln70_131_fu_5082_p0;

assign sext_ln70_132_fu_5145_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign sext_ln70_133_fu_5150_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_4;

assign sext_ln70_133_fu_5150_p1 = sext_ln70_133_fu_5150_p0;

assign sext_ln70_134_fu_5205_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign sext_ln70_135_fu_5210_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign sext_ln70_136_fu_5215_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign sext_ln70_137_fu_5302_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;

assign sext_ln70_138_fu_5307_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;

assign sext_ln70_138_fu_5307_p1 = sext_ln70_138_fu_5307_p0;

assign sext_ln70_139_fu_5313_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_2;

assign sext_ln70_140_fu_5362_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign sext_ln70_141_fu_5367_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign sext_ln70_141_fu_5367_p1 = sext_ln70_141_fu_5367_p0;

assign sext_ln70_142_fu_5371_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign sext_ln70_143_fu_5480_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign sext_ln70_144_fu_5485_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign sext_ln70_144_fu_5485_p1 = sext_ln70_144_fu_5485_p0;

assign sext_ln70_fu_4876_p0 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign sext_ln70_fu_4876_p1 = sext_ln70_fu_4876_p0;

assign sext_ln73_4_fu_5244_p1 = $signed(trunc_ln42_34_fu_5234_p4);

assign sext_ln73_5_fu_5414_p1 = $signed(trunc_ln42_42_fu_5404_p4);

assign sext_ln73_6_fu_5458_p1 = $signed(trunc_ln42_43_fu_5448_p4);

assign sext_ln73_79_fu_4929_p1 = $signed(tmp_fu_4921_p3);

assign sext_ln73_7_fu_5519_p1 = $signed(trunc_ln42_45_fu_5509_p4);

assign sext_ln73_80_fu_5256_p1 = $signed(tmp_90_fu_5248_p3);

assign sext_ln73_81_fu_5268_p1 = $signed(tmp_91_fu_5260_p3);

assign sext_ln73_82_fu_5394_p1 = $signed(tmp_92_fu_5386_p3);

assign sext_ln73_83_fu_5426_p1 = $signed(tmp_93_fu_5418_p3);

assign sext_ln73_84_fu_5438_p1 = $signed(tmp_94_fu_5430_p3);

assign sext_ln73_85_fu_5499_p1 = $signed(tmp_95_fu_5491_p3);

assign sext_ln73_8_fu_5543_p1 = $signed(trunc_ln42_47_fu_5533_p4);

assign sext_ln73_fu_5230_p1 = $signed(trunc_ln42_33_fu_5220_p4);

assign shl_ln111_1_fu_5849_p3 = {{x_13_fu_5807_p2}, {10'd0}};

assign shl_ln111_9_fu_5825_p3 = {{x_11_fu_5757_p2}, {10'd0}};

assign shl_ln111_s_fu_5837_p3 = {{x_12_fu_5782_p2}, {10'd0}};

assign shl_ln_fu_5813_p3 = {{x_fu_5733_p2}, {10'd0}};

assign sub_ln73_39_fu_5442_p2 = ($signed(sext_ln73_84_fu_5438_p1) - $signed(sext_ln73_83_fu_5426_p1));

assign sub_ln73_40_fu_5503_p2 = ($signed(19'd0) - $signed(sext_ln73_85_fu_5499_p1));

assign sub_ln73_fu_5272_p2 = ($signed(sext_ln73_80_fu_5256_p1) - $signed(sext_ln73_81_fu_5268_p1));

assign tmp_90_fu_5248_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign tmp_90_fu_5248_p3 = {{tmp_90_fu_5248_p1}, {8'd0}};

assign tmp_91_fu_5260_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_3;

assign tmp_91_fu_5260_p3 = {{tmp_91_fu_5260_p1}, {5'd0}};

assign tmp_92_fu_5386_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign tmp_92_fu_5386_p3 = {{tmp_92_fu_5386_p1}, {3'd0}};

assign tmp_93_fu_5418_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign tmp_93_fu_5418_p3 = {{tmp_93_fu_5418_p1}, {4'd0}};

assign tmp_94_fu_5430_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_1;

assign tmp_94_fu_5430_p3 = {{tmp_94_fu_5430_p1}, {2'd0}};

assign tmp_95_fu_5491_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig;

assign tmp_95_fu_5491_p3 = {{tmp_95_fu_5491_p1}, {2'd0}};

assign tmp_fu_4921_p1 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_8;

assign tmp_fu_4921_p3 = {{tmp_fu_4921_p1}, {3'd0}};

assign trunc_ln42_15_fu_4911_p4 = {{mul_ln73_244_fu_157_p2[25:10]}};

assign trunc_ln42_16_fu_4939_p4 = {{add_ln73_fu_4933_p2[20:10]}};

assign trunc_ln42_17_fu_4969_p4 = {{mul_ln73_245_fu_171_p2[25:10]}};

assign trunc_ln42_18_fu_4979_p4 = {{mul_ln73_246_fu_186_p2[25:10]}};

assign trunc_ln42_19_fu_4989_p4 = {{mul_ln73_247_fu_162_p2[25:10]}};

assign trunc_ln42_21_fu_5025_p4 = {{mul_ln73_249_fu_156_p2[25:10]}};

assign trunc_ln42_22_fu_5035_p4 = {{mul_ln73_250_fu_183_p2[25:10]}};

assign trunc_ln42_23_fu_5045_p4 = {{mul_ln73_251_fu_178_p2[24:10]}};

assign trunc_ln42_24_fu_5059_p4 = {{mul_ln73_252_fu_161_p2[24:10]}};

assign trunc_ln42_25_fu_5089_p4 = {{mul_ln73_253_fu_175_p2[24:10]}};

assign trunc_ln42_26_fu_5103_p4 = {{mul_ln73_254_fu_173_p2[25:10]}};

assign trunc_ln42_27_fu_5113_p4 = {{mul_ln73_255_fu_189_p2[24:10]}};

assign trunc_ln42_28_fu_5127_p4 = {{mul_ln73_256_fu_159_p2[24:10]}};

assign trunc_ln42_29_fu_5157_p4 = {{mul_ln73_257_fu_174_p2[25:10]}};

assign trunc_ln42_30_fu_5167_p4 = {{mul_ln73_258_fu_185_p2[25:10]}};

assign trunc_ln42_31_fu_5177_p4 = {{mul_ln73_259_fu_154_p2[24:10]}};

assign trunc_ln42_32_fu_5191_p4 = {{mul_ln73_260_fu_181_p2[25:10]}};

assign trunc_ln42_33_fu_5220_p4 = {{mul_ln73_261_fu_176_p2[22:10]}};

assign trunc_ln42_34_fu_5234_p4 = {{mul_ln73_262_fu_167_p2[23:10]}};

assign trunc_ln42_38_fu_5328_p4 = {{mul_ln73_265_fu_179_p2[25:10]}};

assign trunc_ln42_40_fu_5348_p4 = {{mul_ln73_267_fu_160_p2[25:10]}};

assign trunc_ln42_42_fu_5404_p4 = {{add_ln73_15_fu_5398_p2[20:10]}};

assign trunc_ln42_43_fu_5448_p4 = {{sub_ln73_39_fu_5442_p2[20:10]}};

assign trunc_ln42_44_fu_5462_p4 = {{mul_ln73_269_fu_184_p2[22:10]}};

assign trunc_ln42_45_fu_5509_p4 = {{sub_ln73_40_fu_5503_p2[18:10]}};

assign trunc_ln42_47_fu_5533_p4 = {{mul_ln73_271_fu_164_p2[23:10]}};

assign trunc_ln42_48_fu_5547_p4 = {{mul_ln73_272_fu_180_p2[25:10]}};

assign trunc_ln_fu_4891_p4 = {{mul_ln73_fu_158_p2[25:10]}};

assign x_11_fu_5757_p2 = (add_ln58_318_fu_5751_p2 + add_ln58_314_fu_5739_p2);

assign x_12_fu_5782_p2 = (add_ln58_327_fu_5776_p2 + add_ln58_323_fu_5763_p2);

assign x_13_fu_5807_p2 = (add_ln58_336_fu_5801_p2 + add_ln58_332_fu_5788_p2);

assign x_fu_5733_p2 = (add_ln58_309_fu_5727_p2 + add_ln58_305_fu_5714_p2);

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_37_17_5_3_0_config2_mult_s
