-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer3_out_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    layer3_out_empty_n : IN STD_LOGIC;
    layer3_out_read : OUT STD_LOGIC;
    layer3_out_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    layer3_out_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    layer4_out_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    layer4_out_full_n : IN STD_LOGIC;
    layer4_out_write : OUT STD_LOGIC;
    layer4_out_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    layer4_out_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln55_reg_729 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_reg_733 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op113_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage1_iter1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal icmp_ln109_reg_725 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal pY : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal pX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal sX : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal layer3_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp1 : BOOLEAN;
    signal layer4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal icmp_ln109_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln55_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_1_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_pack_fu_365_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_reg_737 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_1_fu_441_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_1_reg_742 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_2_fu_517_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_2_reg_747 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_3_fu_593_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_pack_3_reg_752 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln76_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln76_reg_757 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_689_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_done : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_idle : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ready : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read1 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read2 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld : STD_LOGIC;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ce : STD_LOGIC;
    signal ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp22 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_ignoreCallOp22_grp1 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_storemerge_i_reg_123 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_i_reg_123 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_ignoreCallOp22_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln80_fu_655_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln76_fu_601_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln91_fu_625_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten2_fu_106 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln109_fu_190_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_indvar_flatten2_load : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage1_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal icmp_ln55_2_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_3_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln55_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln55_1_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_fu_313_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_1_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_1_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_fu_325_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln0_1_fu_345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_2_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_2_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_3_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_3_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_4_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_4_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_2_fu_401_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln0_3_fu_421_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_5_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_5_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_6_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_6_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_7_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_7_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_4_fu_477_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln0_5_fu_497_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_8_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_8_fu_511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_9_fu_541_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_9_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln66_10_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_10_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln0_6_fu_553_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln0_7_fu_573_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln66_11_fu_581_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln66_11_fu_587_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln91_fu_619_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln86_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln86_fu_683_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_266 : BOOLEAN;
    signal ap_condition_252 : BOOLEAN;
    signal ap_condition_365 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i : IN STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld : OUT STD_LOGIC;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i : IN STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld : OUT STD_LOGIC;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;


    component myproject_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134 : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start,
        ap_done => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_done,
        ap_idle => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_idle,
        ap_ready => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ready,
        p_read => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read,
        p_read1 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read1,
        p_read2 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read2,
        p_read3 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read3,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i => void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6,
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i => p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4,
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld,
        ap_ce => call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ce);

    flow_control_loop_pipe_U : component myproject_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1)) then 
                        ap_block_pp0_stage1_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg <= ap_const_logic_1;
                elsif ((call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ready = ap_const_logic_1)) then 
                    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                if (((ap_loop_exit_ready = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_11001)) then 
                    ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_storemerge_i_reg_123_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln80_fu_661_p2 = ap_const_lv1_1) and (icmp_ln76_fu_607_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_123 <= ap_const_lv32_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln80_fu_661_p2 = ap_const_lv1_0) and (icmp_ln76_fu_607_p2 = ap_const_lv1_1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_123 <= select_ln86_fu_689_p3;
            elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_phi_reg_pp0_iter1_storemerge_i_reg_123 <= ap_phi_reg_pp0_iter0_storemerge_i_reg_123;
            end if; 
        end if;
    end process;

    indvar_flatten2_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_266)) then
                indvar_flatten2_fu_106 <= add_ln109_fu_190_p2;
            end if;
        end if;
    end process;

    pX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_252)) then
                if ((icmp_ln76_fu_607_p2 = ap_const_lv1_1)) then 
                    pX <= ap_const_lv32_0;
                elsif ((icmp_ln76_fu_607_p2 = ap_const_lv1_0)) then 
                    pX <= add_ln76_fu_601_p2;
                end if;
            end if; 
        end if;
    end process;

    pY_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_365)) then
                if ((icmp_ln80_fu_661_p2 = ap_const_lv1_1)) then 
                    pY <= ap_const_lv32_0;
                elsif ((icmp_ln80_fu_661_p2 = ap_const_lv1_0)) then 
                    pY <= add_ln80_fu_655_p2;
                end if;
            end if; 
        end if;
    end process;

    sX_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_252)) then
                if ((icmp_ln76_fu_607_p2 = ap_const_lv1_1)) then 
                    sX <= ap_const_lv32_0;
                elsif ((icmp_ln76_fu_607_p2 = ap_const_lv1_0)) then 
                    sX <= select_ln91_fu_625_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln55_1_reg_733 <= and_ln55_1_fu_291_p2;
                icmp_ln109_reg_725 <= icmp_ln109_fu_196_p2;
                icmp_ln55_reg_729 <= icmp_ln55_fu_249_p2;
                icmp_ln76_reg_757 <= icmp_ln76_fu_607_p2;
                res_pack_1_reg_742 <= res_pack_1_fu_441_p3;
                res_pack_2_reg_747 <= res_pack_2_fu_517_p3;
                res_pack_3_reg_752 <= res_pack_3_fu_593_p3;
                res_pack_reg_737 <= res_pack_fu_365_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln76_reg_757 = ap_const_lv1_1))) then
                sY <= ap_phi_reg_pp0_iter1_storemerge_i_reg_123;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld = ap_const_logic_1))) then
                void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln109_fu_190_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten2_load) + unsigned(ap_const_lv6_1));
    add_ln76_fu_601_p2 <= std_logic_vector(unsigned(pX) + unsigned(ap_const_lv32_1));
    add_ln80_fu_655_p2 <= std_logic_vector(unsigned(pY) + unsigned(ap_const_lv32_1));
    add_ln86_fu_683_p2 <= std_logic_vector(unsigned(sY) + unsigned(ap_const_lv32_1));
    add_ln91_fu_619_p2 <= std_logic_vector(unsigned(sX) + unsigned(ap_const_lv32_1));
    and_ln55_1_fu_291_p2 <= (icmp_ln55_1_fu_263_p2 and and_ln55_fu_285_p2);
    and_ln55_fu_285_p2 <= (icmp_ln55_3_fu_279_p2 and icmp_ln55_2_fu_273_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_done_reg, ap_block_state1_pp0_stage0_iter0)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage1_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_01001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp1_assign_proc : process(layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_pp0_stage1_11001_ignoreCallOp22_assign_proc : process(ap_enable_reg_pp0_iter1, layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2)
    begin
                ap_block_pp0_stage1_11001_ignoreCallOp22 <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage1_11001_ignoreCallOp22_grp1_assign_proc : process(layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_11001_ignoreCallOp22_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_ignoreCallOp22_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp1_assign_proc : process(layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage1_subdone_grp1 <= ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (layer3_out_empty_n = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_pp0_stage1_iter1_grp2, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_pp0_stage1_iter1_grp2));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state4_pp0_stage1_iter1_grp2_assign_proc : process(layer4_out_full_n, ap_predicate_op113_write_state4)
    begin
                ap_block_state4_pp0_stage1_iter1_grp2 <= ((ap_predicate_op113_write_state4 = ap_const_boolean_1) and (layer4_out_full_n = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2_assign_proc : process(layer4_out_full_n, ap_predicate_op113_write_state4)
    begin
                ap_block_state4_pp0_stage1_iter1_ignore_call9_grp2 <= ((ap_predicate_op113_write_state4 = ap_const_boolean_1) and (layer4_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_252_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_252 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_266_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_266 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_365_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln76_fu_607_p2)
    begin
                ap_condition_365 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln76_fu_607_p2 = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln109_reg_725)
    begin
        if (((icmp_ln109_reg_725 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_phi_reg_pp0_iter0_storemerge_i_reg_123 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op113_write_state4_assign_proc : process(icmp_ln55_reg_729, and_ln55_1_reg_733)
    begin
                ap_predicate_op113_write_state4 <= ((ap_const_lv1_1 = and_ln55_1_reg_733) and (icmp_ln55_reg_729 = ap_const_lv1_1));
    end process;

    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten2_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0, indvar_flatten2_fu_106, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten2_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten2_load <= indvar_flatten2_fu_106;
        end if; 
    end process;


    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_block_pp0_stage1_11001_ignoreCallOp22_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_ignoreCallOp22_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ce <= ap_const_logic_1;
        else 
            call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start <= call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_ap_start_reg;
    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read <= layer3_out_dout(16 - 1 downto 0);
    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read1 <= layer3_out_dout(31 downto 16);
    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read2 <= layer3_out_dout(47 downto 32);
    call_ln52_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_fu_134_p_read3 <= layer3_out_dout(63 downto 48);
    icmp_ln109_fu_196_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten2_load = ap_const_lv6_23) else "0";
    icmp_ln55_1_fu_263_p2 <= "1" when (sY = ap_const_lv32_1) else "0";
    icmp_ln55_2_fu_273_p2 <= "1" when (signed(pY) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_3_fu_279_p2 <= "1" when (signed(pX) > signed(ap_const_lv32_0)) else "0";
    icmp_ln55_fu_249_p2 <= "1" when (sX = ap_const_lv32_1) else "0";
    icmp_ln66_10_fu_561_p2 <= "1" when (signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4) < signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap)) else "0";
    icmp_ln66_11_fu_581_p2 <= "1" when (signed(select_ln0_6_fu_553_p3) < signed(select_ln0_7_fu_573_p3)) else "0";
    icmp_ln66_1_fu_333_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7) < signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3)) else "0";
    icmp_ln66_2_fu_353_p2 <= "1" when (signed(select_ln0_fu_325_p3) < signed(select_ln0_1_fu_345_p3)) else "0";
    icmp_ln66_3_fu_389_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5) < signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1)) else "0";
    icmp_ln66_4_fu_409_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6) < signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2)) else "0";
    icmp_ln66_5_fu_429_p2 <= "1" when (signed(select_ln0_2_fu_401_p3) < signed(select_ln0_3_fu_421_p3)) else "0";
    icmp_ln66_6_fu_465_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4) < signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel)) else "0";
    icmp_ln66_7_fu_485_p2 <= "1" when (signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5) < signed(p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1)) else "0";
    icmp_ln66_8_fu_505_p2 <= "1" when (signed(select_ln0_4_fu_477_p3) < signed(select_ln0_5_fu_497_p3)) else "0";
    icmp_ln66_9_fu_541_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3) < signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8)) else "0";
    icmp_ln66_fu_313_p2 <= "1" when (signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9) < signed(void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2)) else "0";
    icmp_ln76_fu_607_p2 <= "1" when (add_ln76_fu_601_p2 = ap_const_lv32_6) else "0";
    icmp_ln80_fu_661_p2 <= "1" when (add_ln80_fu_655_p2 = ap_const_lv32_6) else "0";
    icmp_ln86_fu_677_p2 <= "1" when (sY = ap_const_lv32_1) else "0";

    layer3_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage1, layer3_out_empty_n, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer3_out_blk_n <= layer3_out_empty_n;
        else 
            layer3_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer3_out_read_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage1_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer3_out_read <= ap_const_logic_1;
        else 
            layer3_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer4_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, layer4_out_full_n, ap_predicate_op113_write_state4, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_grp2)
    begin
        if (((ap_predicate_op113_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer4_out_blk_n <= layer4_out_full_n;
        else 
            layer4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4_out_din <= (((res_pack_3_reg_752 & res_pack_2_reg_747) & res_pack_1_reg_742) & res_pack_reg_737);

    layer4_out_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_predicate_op113_write_state4, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_11001_grp2)
    begin
        if (((ap_predicate_op113_write_state4 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            layer4_out_write <= ap_const_logic_1;
        else 
            layer4_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    res_pack_1_fu_441_p3 <= 
        select_ln0_2_fu_401_p3 when (xor_ln66_5_fu_435_p2(0) = '1') else 
        select_ln0_3_fu_421_p3;
    res_pack_2_fu_517_p3 <= 
        select_ln0_4_fu_477_p3 when (xor_ln66_8_fu_511_p2(0) = '1') else 
        select_ln0_5_fu_497_p3;
    res_pack_3_fu_593_p3 <= 
        select_ln0_6_fu_553_p3 when (xor_ln66_11_fu_587_p2(0) = '1') else 
        select_ln0_7_fu_573_p3;
    res_pack_fu_365_p3 <= 
        select_ln0_fu_325_p3 when (xor_ln66_2_fu_359_p2(0) = '1') else 
        select_ln0_1_fu_345_p3;
    select_ln0_1_fu_345_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 when (xor_ln66_1_fu_339_p2(0) = '1') else 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3;
    select_ln0_2_fu_401_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 when (xor_ln66_3_fu_395_p2(0) = '1') else 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
    select_ln0_3_fu_421_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 when (xor_ln66_4_fu_415_p2(0) = '1') else 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2;
    select_ln0_4_fu_477_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 when (xor_ln66_6_fu_471_p2(0) = '1') else 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
    select_ln0_5_fu_497_p3 <= 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 when (xor_ln66_7_fu_491_p2(0) = '1') else 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1;
    select_ln0_6_fu_553_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 when (xor_ln66_9_fu_547_p2(0) = '1') else 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8;
    select_ln0_7_fu_573_p3 <= 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 when (xor_ln66_10_fu_567_p2(0) = '1') else 
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap;
    select_ln0_fu_325_p3 <= 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 when (xor_ln66_fu_319_p2(0) = '1') else 
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
    select_ln86_fu_689_p3 <= 
        ap_const_lv32_0 when (icmp_ln86_fu_677_p2(0) = '1') else 
        add_ln86_fu_683_p2;
    select_ln91_fu_625_p3 <= 
        ap_const_lv32_0 when (icmp_ln55_fu_249_p2(0) = '1') else 
        add_ln91_fu_619_p2;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln66_10_fu_567_p2 <= (icmp_ln66_10_fu_561_p2 xor ap_const_lv1_1);
    xor_ln66_11_fu_587_p2 <= (icmp_ln66_11_fu_581_p2 xor ap_const_lv1_1);
    xor_ln66_1_fu_339_p2 <= (icmp_ln66_1_fu_333_p2 xor ap_const_lv1_1);
    xor_ln66_2_fu_359_p2 <= (icmp_ln66_2_fu_353_p2 xor ap_const_lv1_1);
    xor_ln66_3_fu_395_p2 <= (icmp_ln66_3_fu_389_p2 xor ap_const_lv1_1);
    xor_ln66_4_fu_415_p2 <= (icmp_ln66_4_fu_409_p2 xor ap_const_lv1_1);
    xor_ln66_5_fu_435_p2 <= (icmp_ln66_5_fu_429_p2 xor ap_const_lv1_1);
    xor_ln66_6_fu_471_p2 <= (icmp_ln66_6_fu_465_p2 xor ap_const_lv1_1);
    xor_ln66_7_fu_491_p2 <= (icmp_ln66_7_fu_485_p2 xor ap_const_lv1_1);
    xor_ln66_8_fu_511_p2 <= (icmp_ln66_8_fu_505_p2 xor ap_const_lv1_1);
    xor_ln66_9_fu_547_p2 <= (icmp_ln66_9_fu_541_p2 xor ap_const_lv1_1);
    xor_ln66_fu_319_p2 <= (icmp_ln66_fu_313_p2 xor ap_const_lv1_1);
end behav;
