-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_0_val1 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val2 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val3 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val5 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val6 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (35 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (35 downto 0) );
end;


architecture behav of myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv26_30A : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100001010";
    constant ap_const_lv24_51 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001010001";
    constant ap_const_lv26_3FFFDB2 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110110010";
    constant ap_const_lv26_224 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000100100";
    constant ap_const_lv26_177 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101110111";
    constant ap_const_lv25_91 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010010001";
    constant ap_const_lv26_2BC : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010111100";
    constant ap_const_lv26_3FFFD79 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110101111001";
    constant ap_const_lv26_3FFFD01 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110100000001";
    constant ap_const_lv25_F1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000011110001";
    constant ap_const_lv26_2E0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001011100000";
    constant ap_const_lv25_96 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010010110";
    constant ap_const_lv26_1C6 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111000110";
    constant ap_const_lv26_3FFFD96 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110010110";
    constant ap_const_lv26_3FFFD26 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110100100110";
    constant ap_const_lv26_253 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001010011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000111";
    constant ap_const_lv15_7FF8 : STD_LOGIC_VECTOR (14 downto 0) := "111111111111000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal trunc_ln_reg_1650 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln42_8_reg_1655 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_10_reg_1660 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_11_reg_1665 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln42_12_reg_1670 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_13_reg_1675 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_1513_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_reg_1680 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_288_fu_1519_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_288_reg_1685 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_295_fu_1525_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_295_reg_1690 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_296_fu_1531_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_296_reg_1695 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_300_fu_1543_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_300_reg_1700 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_9_fu_136_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_2_fu_1487_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_136_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal mul_ln73_fu_137_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln42_4_fu_138_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_2_fu_139_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_120_fu_1349_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_139_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_239_fu_140_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_239_fu_140_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_238_fu_141_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_3_fu_142_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_121_fu_1375_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_142_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_6_fu_143_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_1_fu_1431_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_143_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_1_fu_144_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_fu_1323_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_144_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_241_fu_145_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln42_5_fu_146_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_5_fu_146_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_242_fu_147_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln73_240_fu_148_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_240_fu_148_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_7_fu_149_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_8_fu_150_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_8_fu_150_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_151_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_151_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln70_fu_1289_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_119_fu_1294_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_fu_137_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal mul_ln73_238_fu_141_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln42_1_fu_1309_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln42_fu_151_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_144_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_139_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_239_fu_140_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_142_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_240_fu_148_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_112_fu_1401_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_122_fu_1406_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_241_fu_145_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln42_4_fu_138_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_5_fu_146_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_143_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln42_114_fu_1457_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_123_fu_1462_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_242_fu_147_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln42_7_fu_149_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_8_fu_150_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_136_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_2_fu_1329_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_4_fu_1355_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_6_fu_1381_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_fu_1437_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_3_fu_1339_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_5_fu_1365_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_7_fu_1391_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_9_fu_1421_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_1319_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_299_fu_1537_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_14_fu_1503_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_113_fu_1552_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_3_fu_1549_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln58_291_fu_1567_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln58_fu_1573_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_115_fu_1555_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_292_fu_1577_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_290_fu_1562_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_293_fu_1583_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_289_fu_1558_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_298_fu_1599_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_301_fu_1603_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_297_fu_1595_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_fu_1589_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_1614_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal x_10_fu_1608_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln111_8_fu_1626_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln110_fu_1622_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal sext_ln18_fu_1634_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_mul_16s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_8ns_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myproject_mul_16s_11s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_9ns_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;



begin
    mul_16s_11ns_26_1_1_U408 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_9_fu_136_p0,
        din1 => mul_ln42_9_fu_136_p1,
        dout => mul_ln42_9_fu_136_p2);

    mul_16s_8ns_24_1_1_U409 : component myproject_mul_16s_8ns_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 8,
        dout_WIDTH => 24)
    port map (
        din0 => sext_ln70_119_fu_1294_p0,
        din1 => mul_ln73_fu_137_p1,
        dout => mul_ln73_fu_137_p2);

    mul_16s_11s_26_1_1_U410 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => sext_ln42_112_fu_1401_p0,
        din1 => mul_ln42_4_fu_138_p1,
        dout => mul_ln42_4_fu_138_p2);

    mul_16s_11ns_26_1_1_U411 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_2_fu_139_p0,
        din1 => mul_ln42_2_fu_139_p1,
        dout => mul_ln42_2_fu_139_p2);

    mul_16s_10ns_26_1_1_U412 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_239_fu_140_p0,
        din1 => mul_ln73_239_fu_140_p1,
        dout => mul_ln73_239_fu_140_p2);

    mul_16s_9ns_25_1_1_U413 : component myproject_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => sext_ln70_fu_1289_p0,
        din1 => mul_ln73_238_fu_141_p1,
        dout => mul_ln73_238_fu_141_p2);

    mul_16s_11ns_26_1_1_U414 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_3_fu_142_p0,
        din1 => mul_ln42_3_fu_142_p1,
        dout => mul_ln42_3_fu_142_p2);

    mul_16s_11s_26_1_1_U415 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_6_fu_143_p0,
        din1 => mul_ln42_6_fu_143_p1,
        dout => mul_ln42_6_fu_143_p2);

    mul_16s_11s_26_1_1_U416 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_1_fu_144_p0,
        din1 => mul_ln42_1_fu_144_p1,
        dout => mul_ln42_1_fu_144_p2);

    mul_16s_9ns_25_1_1_U417 : component myproject_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => sext_ln70_122_fu_1406_p0,
        din1 => mul_ln73_241_fu_145_p1,
        dout => mul_ln73_241_fu_145_p2);

    mul_16s_11ns_26_1_1_U418 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_5_fu_146_p0,
        din1 => mul_ln42_5_fu_146_p1,
        dout => mul_ln42_5_fu_146_p2);

    mul_16s_9ns_25_1_1_U419 : component myproject_mul_16s_9ns_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 25)
    port map (
        din0 => sext_ln70_123_fu_1462_p0,
        din1 => mul_ln73_242_fu_147_p1,
        dout => mul_ln73_242_fu_147_p2);

    mul_16s_10ns_26_1_1_U420 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_240_fu_148_p0,
        din1 => mul_ln73_240_fu_148_p1,
        dout => mul_ln73_240_fu_148_p2);

    mul_16s_11s_26_1_1_U421 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => sext_ln42_114_fu_1457_p0,
        din1 => mul_ln42_7_fu_149_p1,
        dout => mul_ln42_7_fu_149_p2);

    mul_16s_11s_26_1_1_U422 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_8_fu_150_p0,
        din1 => mul_ln42_8_fu_150_p1,
        dout => mul_ln42_8_fu_150_p2);

    mul_16s_11ns_26_1_1_U423 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_fu_151_p0,
        din1 => mul_ln42_fu_151_p1,
        dout => mul_ln42_fu_151_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln58_288_reg_1685 <= add_ln58_288_fu_1519_p2;
                add_ln58_295_reg_1690 <= add_ln58_295_fu_1525_p2;
                add_ln58_296_reg_1695 <= add_ln58_296_fu_1531_p2;
                add_ln58_300_reg_1700 <= add_ln58_300_fu_1543_p2;
                add_ln58_reg_1680 <= add_ln58_fu_1513_p2;
                trunc_ln42_10_reg_1660 <= mul_ln42_6_fu_143_p2(25 downto 10);
                trunc_ln42_11_reg_1665 <= mul_ln73_242_fu_147_p2(24 downto 10);
                trunc_ln42_12_reg_1670 <= mul_ln42_7_fu_149_p2(25 downto 10);
                trunc_ln42_13_reg_1675 <= mul_ln42_8_fu_150_p2(25 downto 10);
                trunc_ln42_8_reg_1655 <= mul_ln73_241_fu_145_p2(24 downto 10);
                trunc_ln_reg_1650 <= mul_ln73_fu_137_p2(23 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln58_288_fu_1519_p2 <= std_logic_vector(unsigned(trunc_ln42_6_fu_1381_p4) + unsigned(trunc_ln42_s_fu_1437_p4));
    add_ln58_289_fu_1558_p2 <= std_logic_vector(unsigned(add_ln58_288_reg_1685) + unsigned(add_ln58_reg_1680));
    add_ln58_290_fu_1562_p2 <= std_logic_vector(unsigned(trunc_ln42_13_reg_1675) + unsigned(sext_ln42_113_fu_1552_p1));
    add_ln58_291_fu_1567_p2 <= std_logic_vector(signed(sext_ln73_3_fu_1549_p1) + signed(ap_const_lv15_7FF8));
    add_ln58_292_fu_1577_p2 <= std_logic_vector(signed(sext_ln58_fu_1573_p1) + signed(sext_ln42_115_fu_1555_p1));
    add_ln58_293_fu_1583_p2 <= std_logic_vector(unsigned(add_ln58_292_fu_1577_p2) + unsigned(add_ln58_290_fu_1562_p2));
    add_ln58_295_fu_1525_p2 <= std_logic_vector(unsigned(trunc_ln42_3_fu_1339_p4) + unsigned(trunc_ln42_5_fu_1365_p4));
    add_ln58_296_fu_1531_p2 <= std_logic_vector(unsigned(trunc_ln42_7_fu_1391_p4) + unsigned(trunc_ln42_9_fu_1421_p4));
    add_ln58_297_fu_1595_p2 <= std_logic_vector(unsigned(add_ln58_296_reg_1695) + unsigned(add_ln58_295_reg_1690));
    add_ln58_298_fu_1599_p2 <= std_logic_vector(unsigned(trunc_ln42_10_reg_1660) + unsigned(trunc_ln42_12_reg_1670));
    add_ln58_299_fu_1537_p2 <= std_logic_vector(signed(sext_ln42_fu_1319_p1) + signed(ap_const_lv16_7));
    add_ln58_300_fu_1543_p2 <= std_logic_vector(unsigned(add_ln58_299_fu_1537_p2) + unsigned(trunc_ln42_14_fu_1503_p4));
    add_ln58_301_fu_1603_p2 <= std_logic_vector(unsigned(add_ln58_300_reg_1700) + unsigned(add_ln58_298_fu_1599_p2));
    add_ln58_fu_1513_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_1329_p4) + unsigned(trunc_ln42_4_fu_1355_p4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sext_ln110_fu_1622_p1;
    ap_return_1 <= sext_ln18_fu_1634_p1;
    mul_ln42_1_fu_144_p0 <= sext_ln73_fu_1323_p1(16 - 1 downto 0);
    mul_ln42_1_fu_144_p1 <= ap_const_lv26_3FFFD01(11 - 1 downto 0);
    mul_ln42_2_fu_139_p0 <= sext_ln70_120_fu_1349_p1(16 - 1 downto 0);
    mul_ln42_2_fu_139_p1 <= ap_const_lv26_224(11 - 1 downto 0);
    mul_ln42_3_fu_142_p0 <= sext_ln70_121_fu_1375_p1(16 - 1 downto 0);
    mul_ln42_3_fu_142_p1 <= ap_const_lv26_2BC(11 - 1 downto 0);
    mul_ln42_4_fu_138_p1 <= ap_const_lv26_3FFFDB2(11 - 1 downto 0);
    mul_ln42_5_fu_146_p0 <= sext_ln73_1_fu_1431_p1(16 - 1 downto 0);
    mul_ln42_5_fu_146_p1 <= ap_const_lv26_2E0(11 - 1 downto 0);
    mul_ln42_6_fu_143_p0 <= sext_ln73_1_fu_1431_p1(16 - 1 downto 0);
    mul_ln42_6_fu_143_p1 <= ap_const_lv26_3FFFD79(11 - 1 downto 0);
    mul_ln42_7_fu_149_p1 <= ap_const_lv26_3FFFD96(11 - 1 downto 0);
    mul_ln42_8_fu_150_p0 <= sext_ln73_2_fu_1487_p1(16 - 1 downto 0);
    mul_ln42_8_fu_150_p1 <= ap_const_lv26_3FFFD26(11 - 1 downto 0);
    mul_ln42_9_fu_136_p0 <= sext_ln73_2_fu_1487_p1(16 - 1 downto 0);
    mul_ln42_9_fu_136_p1 <= ap_const_lv26_30A(11 - 1 downto 0);
    mul_ln42_fu_151_p0 <= sext_ln73_fu_1323_p1(16 - 1 downto 0);
    mul_ln42_fu_151_p1 <= ap_const_lv26_253(11 - 1 downto 0);
    mul_ln73_238_fu_141_p1 <= ap_const_lv25_91(9 - 1 downto 0);
    mul_ln73_239_fu_140_p0 <= sext_ln70_120_fu_1349_p1(16 - 1 downto 0);
    mul_ln73_239_fu_140_p1 <= ap_const_lv26_177(10 - 1 downto 0);
    mul_ln73_240_fu_148_p0 <= sext_ln70_121_fu_1375_p1(16 - 1 downto 0);
    mul_ln73_240_fu_148_p1 <= ap_const_lv26_1C6(10 - 1 downto 0);
    mul_ln73_241_fu_145_p1 <= ap_const_lv25_F1(9 - 1 downto 0);
    mul_ln73_242_fu_147_p1 <= ap_const_lv25_96(9 - 1 downto 0);
    mul_ln73_fu_137_p1 <= ap_const_lv24_51(8 - 1 downto 0);
        sext_ln110_fu_1622_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_1614_p3),36));

        sext_ln18_fu_1634_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln111_8_fu_1626_p3),36));

    sext_ln42_112_fu_1401_p0 <= data_4_val5;
        sext_ln42_113_fu_1552_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_8_reg_1655),16));

    sext_ln42_114_fu_1457_p0 <= data_6_val7;
        sext_ln42_115_fu_1555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_11_reg_1665),16));

        sext_ln42_fu_1319_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln42_1_fu_1309_p4),16));

        sext_ln58_fu_1573_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_291_fu_1567_p2),16));

    sext_ln70_119_fu_1294_p0 <= data_0_val1;
        sext_ln70_120_fu_1349_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val3),26));

        sext_ln70_121_fu_1375_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_3_val4),26));

    sext_ln70_122_fu_1406_p0 <= data_4_val5;
    sext_ln70_123_fu_1462_p0 <= data_6_val7;
    sext_ln70_fu_1289_p0 <= data_0_val1;
        sext_ln73_1_fu_1431_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_5_val6),26));

        sext_ln73_2_fu_1487_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_7_val8),26));

        sext_ln73_3_fu_1549_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_1650),15));

        sext_ln73_fu_1323_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val2),26));

    shl_ln111_8_fu_1626_p3 <= (x_10_fu_1608_p2 & ap_const_lv10_0);
    shl_ln_fu_1614_p3 <= (x_fu_1589_p2 & ap_const_lv10_0);
    trunc_ln42_14_fu_1503_p4 <= mul_ln42_9_fu_136_p2(25 downto 10);
    trunc_ln42_1_fu_1309_p4 <= mul_ln73_238_fu_141_p2(24 downto 10);
    trunc_ln42_2_fu_1329_p4 <= mul_ln42_fu_151_p2(25 downto 10);
    trunc_ln42_3_fu_1339_p4 <= mul_ln42_1_fu_144_p2(25 downto 10);
    trunc_ln42_4_fu_1355_p4 <= mul_ln42_2_fu_139_p2(25 downto 10);
    trunc_ln42_5_fu_1365_p4 <= mul_ln73_239_fu_140_p2(25 downto 10);
    trunc_ln42_6_fu_1381_p4 <= mul_ln42_3_fu_142_p2(25 downto 10);
    trunc_ln42_7_fu_1391_p4 <= mul_ln73_240_fu_148_p2(25 downto 10);
    trunc_ln42_9_fu_1421_p4 <= mul_ln42_4_fu_138_p2(25 downto 10);
    trunc_ln42_s_fu_1437_p4 <= mul_ln42_5_fu_146_p2(25 downto 10);
    x_10_fu_1608_p2 <= std_logic_vector(unsigned(add_ln58_301_fu_1603_p2) + unsigned(add_ln58_297_fu_1595_p2));
    x_fu_1589_p2 <= std_logic_vector(unsigned(add_ln58_293_fu_1583_p2) + unsigned(add_ln58_289_fu_1558_p2));
end behav;
