-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    table_out_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    table_out_ce0 : OUT STD_LOGIC;
    table_out_we0 : OUT STD_LOGIC;
    table_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv6_23 : STD_LOGIC_VECTOR (5 downto 0) := "100011";
    constant ap_const_lv6_27 : STD_LOGIC_VECTOR (5 downto 0) := "100111";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv35_0 : STD_LOGIC_VECTOR (34 downto 0) := "00000000000000000000000000000000000";
    constant ap_const_lv6_28 : STD_LOGIC_VECTOR (5 downto 0) := "101000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_7E : STD_LOGIC_VECTOR (7 downto 0) := "01111110";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv12_FF6 : STD_LOGIC_VECTOR (11 downto 0) := "111111110110";
    constant ap_const_lv11_A : STD_LOGIC_VECTOR (10 downto 0) := "00000001010";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv11_7F5 : STD_LOGIC_VECTOR (10 downto 0) := "11111110101";
    constant ap_const_lv10_201 : STD_LOGIC_VECTOR (9 downto 0) := "1000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv12_8 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_const_lv12_9 : STD_LOGIC_VECTOR (11 downto 0) := "000000001001";
    constant ap_const_lv11_36 : STD_LOGIC_VECTOR (10 downto 0) := "00000110110";
    constant ap_const_lv18_3FFFF : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111111";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv11_12 : STD_LOGIC_VECTOR (10 downto 0) := "00000010010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv54_3FFFFFFFFFFFFF : STD_LOGIC_VECTOR (53 downto 0) := "111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln151_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal i_1_reg_1161 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_1_reg_1161_pp0_iter1_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter9_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter10_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter11_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter12_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter13_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter14_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter15_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter16_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter17_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter18_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal i_1_reg_1161_pp0_iter19_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal x_fu_215_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal x_reg_1170 : STD_LOGIC_VECTOR (34 downto 0);
    signal trunc_ln138_fu_231_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln138_reg_1178 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln138_fu_235_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln138_reg_1183 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln138_1_fu_241_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln138_1_reg_1188 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln138_1_fu_247_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln138_1_reg_1193 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln138_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln138_reg_1198 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln157_fu_412_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln157_reg_1203 : STD_LOGIC_VECTOR (30 downto 0);
    signal x_2_fu_427_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_2_reg_1208 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_reg_1213 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_reg_1218 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1218_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1218_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1228 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln159_1_fu_458_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal trunc_ln159_1_reg_1233 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln159_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_reg_1238 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_reg_1238_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_reg_1238_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln159_fu_488_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal select_ln159_reg_1244 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln159_1_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_1_reg_1251 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln159_1_fu_527_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln159_1_reg_1256 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln159_2_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_2_reg_1264 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_2_reg_1264_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln159_4_fu_541_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln159_4_reg_1270 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln159_4_reg_1270_pp0_iter19_reg : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln159_4_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_4_reg_1276 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_561_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1281 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_6_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_6_reg_1286 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_6_reg_1286_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln159_5_fu_613_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_5_reg_1291 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln159_7_fu_619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_7_reg_1299 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_7_reg_1299_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1306 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1306_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_0_i_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lD_0_i_reg_1313 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln159_8_fu_653_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln159_8_reg_1320 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln159_3_fu_702_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln159_3_reg_1325 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln159_2_fu_727_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln159_2_reg_1330 : STD_LOGIC_VECTOR (17 downto 0);
    signal and_ln159_9_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_9_reg_1335 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_i_fu_763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_i_reg_1340 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_i_fu_817_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_i_reg_1347 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_1_fu_836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_1_reg_1352 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_fu_894_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_reg_1357 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_reg_1364 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln151_fu_933_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_166 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln151_fu_205_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (10 downto 0);
    signal table_out_we0_local : STD_LOGIC;
    signal exp_x_fu_1133_p9 : STD_LOGIC_VECTOR (15 downto 0);
    signal table_out_ce0_local : STD_LOGIC;
    signal trunc_ln137_fu_211_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_223_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_fu_223_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln138_fu_263_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_272_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_286_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln138_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln138_1_fu_305_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln138_fu_308_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln138_2_fu_317_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln138_1_fu_320_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal icmp_ln138_1_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln138_fu_312_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal shl_ln138_fu_324_p2 : STD_LOGIC_VECTOR (34 downto 0);
    signal cond42_i_i_i_in_fu_329_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal phi_ln138_1_fu_293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln138_2_fu_337_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal zext_ln138_3_fu_341_p1 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln138_2_fu_345_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal lshr_ln138_1_fu_351_p4 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_3_fu_365_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln138_2_fu_381_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln138_fu_373_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln138_3_fu_386_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln138_3_fu_390_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln138_4_fu_361_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln138_5_fu_396_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal pi_assign_fu_400_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal xor_ln_fu_416_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln157_fu_423_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_183_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bitcast_ln716_fu_434_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln159_fu_438_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln159_1_cast_fu_471_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln159_1_fu_478_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal sub_ln159_fu_482_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal zext_ln159_fu_468_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln159_1_fu_495_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_fu_511_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln159_2_fu_501_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln159_3_fu_517_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln159_2_fu_521_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln159_1_fu_551_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_561_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln159_4_fu_569_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln159_1_fu_577_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln159_3_fu_581_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_10_fu_587_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln159_4_fu_603_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tobool134_i_fu_639_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln159_8_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool134_i_fu_639_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln159_2_fu_669_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal ashr_ln159_fu_672_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal icmp_ln159_3_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln159_5_fu_677_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln159_5_fu_662_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln159_1cast_fu_694_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln159_5_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln159_fu_697_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln159_2_fu_681_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal cond64_i_fu_710_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln159_3_fu_723_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_9_fu_733_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_2_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_715_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_10_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln159_6_fu_784_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal lshr_ln159_fu_787_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal lshr_ln159_1_fu_792_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_13_fu_804_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_10_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_11_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_10_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_9_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_9_fu_769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_12_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_14_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_11_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln159_13_fu_853_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln159_5_fu_875_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_1_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_11_fu_880_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_fu_894_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_886_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal ref_tmp_i_i_fu_943_p7 : STD_LOGIC_VECTOR (17 downto 0);
    signal ref_tmp_i_i_fu_943_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_fu_943_p9 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_11_fu_964_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln159_1_fu_982_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_4_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_5_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cond193_i_fu_991_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_icmp_ln159_749_fu_1007_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_12_fu_1018_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_fu_1030_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_fu_1030_p7 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_fu_1030_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln159_4_fu_977_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_5_fu_1050_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_13_fu_1056_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln159_2_fu_1061_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_6_fu_1067_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_0_i_fu_1012_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_7_fu_1078_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_0_i_fu_1030_p9 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_7_fu_1084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_8_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_6_fu_1072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln159_3_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln159_8_fu_1110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_14_fu_1115_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln159_15_fu_1121_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exp_x_fu_1133_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_x_fu_1133_p6 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_x_fu_1133_p7 : STD_LOGIC_VECTOR (15 downto 0);
    signal exp_x_fu_1133_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter17_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter18_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter19_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_223_p0 : STD_LOGIC_VECTOR (34 downto 0);
    signal tmp_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_286_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_561_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool134_i_fu_639_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_2_i_fu_894_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_ones_2_i_fu_894_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_ones_2_i_fu_894_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal Range1_all_zeros_2_i_fu_913_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_fu_943_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_fu_943_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_tmp_i_i_fu_943_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_fu_1030_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_fu_1030_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal neg_src_0_i_fu_1030_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal exp_x_fu_1133_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal exp_x_fu_1133_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal exp_x_fu_1133_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component myproject_fpext_32ns_64_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component myproject_fexp_32ns_32ns_32_13_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myproject_ctlz_35_35_1_1 IS
    generic (
        din_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (34 downto 0);
        dout : OUT STD_LOGIC_VECTOR (34 downto 0) );
    end component;


    component myproject_bitselect_1ns_35ns_32s_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (34 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myproject_bitselect_1ns_54ns_32ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (53 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myproject_bitselect_1ns_54ns_32s_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (53 downto 0);
        sel : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myproject_sparsemux_7_2_1_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (0 downto 0);
        din1 : IN STD_LOGIC_VECTOR (0 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        def : IN STD_LOGIC_VECTOR (0 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myproject_sparsemux_7_2_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (17 downto 0);
        def : IN STD_LOGIC_VECTOR (17 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component myproject_sparsemux_7_2_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        def : IN STD_LOGIC_VECTOR (15 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component myproject_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fpext_32ns_64_2_no_dsp_1_U436 : component myproject_fpext_32ns_64_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_4_reg_1213,
        ce => ap_const_logic_1,
        dout => grp_fu_183_p1);

    fexp_32ns_32ns_32_13_full_dsp_1_U437 : component myproject_fexp_32ns_32ns_32_13_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_const_lv32_0,
        din1 => x_2_reg_1208,
        ce => ap_const_logic_1,
        dout => grp_fu_186_p2);

    ctlz_35_35_1_1_U438 : component myproject_ctlz_35_35_1_1
    generic map (
        din_WIDTH => 35,
        dout_WIDTH => 35)
    port map (
        din => tmp_fu_223_p1,
        dout => tmp_fu_223_p3);

    bitselect_1ns_35ns_32s_1_1_1_U439 : component myproject_bitselect_1ns_35ns_32s_1_1_1
    generic map (
        DATAWIDTH => 35,
        ADDRWIDTH => 32)
    port map (
        din => x_reg_1170,
        sel => tmp_2_fu_286_p2,
        dout => tmp_2_fu_286_p3);

    bitselect_1ns_54ns_32ns_1_1_1_U440 : component myproject_bitselect_1ns_54ns_32ns_1_1_1
    generic map (
        DATAWIDTH => 54,
        ADDRWIDTH => 32)
    port map (
        din => select_ln159_fu_488_p3,
        sel => tmp_7_fu_561_p2,
        dout => tmp_7_fu_561_p3);

    bitselect_1ns_54ns_32s_1_1_1_U441 : component myproject_bitselect_1ns_54ns_32s_1_1_1
    generic map (
        DATAWIDTH => 54,
        ADDRWIDTH => 32)
    port map (
        din => select_ln159_fu_488_p3,
        sel => tobool134_i_fu_639_p2,
        dout => tobool134_i_fu_639_p3);

    sparsemux_7_2_1_1_1_U442 : component myproject_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => Range1_all_ones_2_i_fu_894_p2,
        din1 => lD_0_i_reg_1313,
        din2 => xor_ln159_9_fu_769_p2,
        def => Range1_all_ones_2_i_fu_894_p7,
        sel => sel_tmp_fu_886_p3,
        dout => Range1_all_ones_2_i_fu_894_p9);

    sparsemux_7_2_1_1_1_U443 : component myproject_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => Range1_all_zeros_2_i_fu_913_p2,
        din1 => xor_ln159_1_fu_836_p2,
        din2 => Range1_all_zeros_2_i_fu_913_p6,
        def => Range1_all_zeros_2_i_fu_913_p7,
        sel => sel_tmp_fu_886_p3,
        dout => Range1_all_zeros_2_i_fu_913_p9);

    sparsemux_7_2_18_1_1_U444 : component myproject_sparsemux_7_2_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 18,
        CASE1 => "01",
        din1_WIDTH => 18,
        CASE2 => "00",
        din2_WIDTH => 18,
        def_WIDTH => 18,
        sel_WIDTH => 2,
        dout_WIDTH => 18)
    port map (
        din0 => trunc_ln159_4_reg_1270_pp0_iter19_reg,
        din1 => add_ln159_2_reg_1330,
        din2 => select_ln159_3_reg_1325,
        def => ref_tmp_i_i_fu_943_p7,
        sel => ref_tmp_i_i_fu_943_p8,
        dout => ref_tmp_i_i_fu_943_p9);

    sparsemux_7_2_1_1_1_U445 : component myproject_sparsemux_7_2_1_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 1,
        CASE1 => "01",
        din1_WIDTH => 1,
        CASE2 => "00",
        din2_WIDTH => 1,
        def_WIDTH => 1,
        sel_WIDTH => 2,
        dout_WIDTH => 1)
    port map (
        din0 => neg_src_0_i_fu_1030_p2,
        din1 => neg_src_0_i_fu_1030_p4,
        din2 => ap_const_lv1_0,
        def => neg_src_0_i_fu_1030_p7,
        sel => neg_src_0_i_fu_1030_p8,
        dout => neg_src_0_i_fu_1030_p9);

    sparsemux_7_2_16_1_1_U446 : component myproject_sparsemux_7_2_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 16,
        CASE1 => "01",
        din1_WIDTH => 16,
        CASE2 => "00",
        din2_WIDTH => 16,
        def_WIDTH => 16,
        sel_WIDTH => 2,
        dout_WIDTH => 16)
    port map (
        din0 => ap_const_lv16_0,
        din1 => exp_x_fu_1133_p4,
        din2 => exp_x_fu_1133_p6,
        def => exp_x_fu_1133_p7,
        sel => exp_x_fu_1133_p8,
        dout => exp_x_fu_1133_p9);

    flow_control_loop_pipe_sequential_init_U : component myproject_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter19_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln151_fu_199_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_166 <= add_ln151_fu_205_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_166 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                Range1_all_ones_2_i_reg_1357 <= Range1_all_ones_2_i_fu_894_p9;
                Range1_all_zeros_2_i_reg_1364 <= Range1_all_zeros_2_i_fu_913_p9;
                Range2_all_ones_1_i_reg_1347 <= Range2_all_ones_1_i_fu_817_p3;
                add_ln159_2_reg_1330 <= add_ln159_2_fu_727_p2;
                add_ln159_5_reg_1291 <= add_ln159_5_fu_613_p2;
                and_ln159_9_reg_1335 <= and_ln159_9_fu_752_p2;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
                ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
                ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                carry_1_i_reg_1340 <= carry_1_i_fu_763_p2;
                i_1_reg_1161_pp0_iter10_reg <= i_1_reg_1161_pp0_iter9_reg;
                i_1_reg_1161_pp0_iter11_reg <= i_1_reg_1161_pp0_iter10_reg;
                i_1_reg_1161_pp0_iter12_reg <= i_1_reg_1161_pp0_iter11_reg;
                i_1_reg_1161_pp0_iter13_reg <= i_1_reg_1161_pp0_iter12_reg;
                i_1_reg_1161_pp0_iter14_reg <= i_1_reg_1161_pp0_iter13_reg;
                i_1_reg_1161_pp0_iter15_reg <= i_1_reg_1161_pp0_iter14_reg;
                i_1_reg_1161_pp0_iter16_reg <= i_1_reg_1161_pp0_iter15_reg;
                i_1_reg_1161_pp0_iter17_reg <= i_1_reg_1161_pp0_iter16_reg;
                i_1_reg_1161_pp0_iter18_reg <= i_1_reg_1161_pp0_iter17_reg;
                i_1_reg_1161_pp0_iter19_reg <= i_1_reg_1161_pp0_iter18_reg;
                i_1_reg_1161_pp0_iter2_reg <= i_1_reg_1161_pp0_iter1_reg;
                i_1_reg_1161_pp0_iter3_reg <= i_1_reg_1161_pp0_iter2_reg;
                i_1_reg_1161_pp0_iter4_reg <= i_1_reg_1161_pp0_iter3_reg;
                i_1_reg_1161_pp0_iter5_reg <= i_1_reg_1161_pp0_iter4_reg;
                i_1_reg_1161_pp0_iter6_reg <= i_1_reg_1161_pp0_iter5_reg;
                i_1_reg_1161_pp0_iter7_reg <= i_1_reg_1161_pp0_iter6_reg;
                i_1_reg_1161_pp0_iter8_reg <= i_1_reg_1161_pp0_iter7_reg;
                i_1_reg_1161_pp0_iter9_reg <= i_1_reg_1161_pp0_iter8_reg;
                icmp_ln159_1_reg_1251 <= icmp_ln159_1_fu_505_p2;
                icmp_ln159_2_reg_1264 <= icmp_ln159_2_fu_535_p2;
                icmp_ln159_2_reg_1264_pp0_iter19_reg <= icmp_ln159_2_reg_1264;
                icmp_ln159_4_reg_1276 <= icmp_ln159_4_fu_545_p2;
                icmp_ln159_6_reg_1286 <= icmp_ln159_6_fu_597_p2;
                icmp_ln159_6_reg_1286_pp0_iter19_reg <= icmp_ln159_6_reg_1286;
                icmp_ln159_7_reg_1299 <= icmp_ln159_7_fu_619_p2;
                icmp_ln159_7_reg_1299_pp0_iter19_reg <= icmp_ln159_7_reg_1299;
                icmp_ln159_reg_1238 <= icmp_ln159_fu_462_p2;
                icmp_ln159_reg_1238_pp0_iter18_reg <= icmp_ln159_reg_1238;
                icmp_ln159_reg_1238_pp0_iter19_reg <= icmp_ln159_reg_1238_pp0_iter18_reg;
                lD_0_i_reg_1313 <= lD_0_i_fu_647_p2;
                select_ln159_1_reg_1256 <= select_ln159_1_fu_527_p3;
                select_ln159_3_reg_1325 <= select_ln159_3_fu_702_p3;
                select_ln159_reg_1244 <= select_ln159_fu_488_p3;
                tmp_12_reg_1306 <= add_ln159_4_fu_603_p2(11 downto 11);
                tmp_12_reg_1306_pp0_iter19_reg <= tmp_12_reg_1306;
                tmp_4_reg_1213 <= grp_fu_186_p2;
                tmp_5_reg_1218 <= bitcast_ln716_fu_434_p1(63 downto 63);
                tmp_5_reg_1218_pp0_iter18_reg <= tmp_5_reg_1218;
                tmp_5_reg_1218_pp0_iter19_reg <= tmp_5_reg_1218_pp0_iter18_reg;
                tmp_6_reg_1228 <= bitcast_ln716_fu_434_p1(62 downto 52);
                tmp_7_reg_1281 <= tmp_7_fu_561_p3;
                trunc_ln159_1_reg_1233 <= trunc_ln159_1_fu_458_p1;
                trunc_ln159_4_reg_1270 <= trunc_ln159_4_fu_541_p1;
                trunc_ln159_4_reg_1270_pp0_iter19_reg <= trunc_ln159_4_reg_1270;
                trunc_ln159_8_reg_1320 <= trunc_ln159_8_fu_653_p1;
                    x_2_reg_1208(30 downto 0) <= x_2_fu_427_p3(30 downto 0);
                xor_ln159_1_reg_1352 <= xor_ln159_1_fu_836_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln138_1_reg_1188 <= add_ln138_1_fu_241_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                i_1_reg_1161 <= ap_sig_allocacmp_i_1;
                i_1_reg_1161_pp0_iter1_reg <= i_1_reg_1161;
                icmp_ln138_reg_1198 <= icmp_ln138_fu_258_p2;
                sub_ln138_1_reg_1193 <= sub_ln138_1_fu_247_p2;
                sub_ln138_reg_1183 <= sub_ln138_fu_235_p2;
                trunc_ln138_reg_1178 <= trunc_ln138_fu_231_p1;
                trunc_ln157_reg_1203 <= trunc_ln157_fu_412_p1;
                    x_reg_1170(34 downto 25) <= x_fu_215_p3(34 downto 25);
            end if;
        end if;
    end process;
    x_reg_1170(24 downto 0) <= "0000000000000000000000000";
    x_2_reg_1208(31) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Range1_all_ones_2_i_fu_894_p2 <= (lD_0_i_reg_1313 and Range2_all_ones_1_i_fu_817_p3);
    Range1_all_ones_2_i_fu_894_p7 <= "X";
    Range1_all_zeros_2_i_fu_913_p2 <= (xor_ln159_1_fu_836_p2 and icmp_ln159_12_fu_841_p2);
    Range1_all_zeros_2_i_fu_913_p6 <= (xor_ln159_9_fu_769_p2 or icmp_ln159_14_fu_858_p2);
    Range1_all_zeros_2_i_fu_913_p7 <= "X";
    Range2_all_ones_1_i_fu_817_p3 <= 
        icmp_ln159_11_fu_798_p2 when (icmp_ln159_10_fu_779_p2(0) = '1') else 
        xor_ln159_10_fu_811_p2;
    add_ln138_1_fu_241_p2 <= std_logic_vector(unsigned(sub_ln138_fu_235_p2) + unsigned(ap_const_lv6_27));
    add_ln138_2_fu_345_p2 <= std_logic_vector(unsigned(zext_ln138_2_fu_337_p1) + unsigned(zext_ln138_3_fu_341_p1));
    add_ln138_3_fu_390_p2 <= std_logic_vector(unsigned(select_ln138_fu_373_p3) + unsigned(sext_ln138_3_fu_386_p1));
    add_ln138_fu_263_p2 <= std_logic_vector(unsigned(sub_ln138_reg_1183) + unsigned(ap_const_lv6_28));
    add_ln151_fu_205_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv11_1));
    add_ln159_1_fu_551_p2 <= std_logic_vector(unsigned(trunc_ln159_2_fu_501_p1) + unsigned(ap_const_lv11_7F5));
    add_ln159_2_fu_727_p2 <= std_logic_vector(unsigned(select_ln159_2_fu_681_p3) + unsigned(zext_ln159_3_fu_723_p1));
    add_ln159_3_fu_581_p2 <= std_logic_vector(signed(sext_ln159_1_fu_577_p1) + signed(zext_ln159_fu_468_p1));
    add_ln159_4_fu_603_p2 <= std_logic_vector(unsigned(sub_ln159_1_fu_495_p2) + unsigned(ap_const_lv12_8));
    add_ln159_5_fu_613_p2 <= std_logic_vector(unsigned(sub_ln159_1_fu_495_p2) + unsigned(ap_const_lv12_9));
    add_ln159_fu_511_p2 <= std_logic_vector(unsigned(sub_ln159_1_fu_495_p2) + unsigned(ap_const_lv12_FF6));
    and_ln159_10_fu_757_p2 <= (tmp_8_fu_715_p3 and and_ln159_9_fu_752_p2);
    and_ln159_11_fu_880_p2 <= (or_ln159_5_fu_875_p2 and icmp_ln159_13_fu_853_p2);
    and_ln159_12_fu_1018_p2 <= (tmp_5_reg_1218_pp0_iter19_reg and icmp_ln159_7_reg_1299_pp0_iter19_reg);
    and_ln159_13_fu_1056_p2 <= (xor_ln159_5_fu_1050_p2 and icmp_ln159_7_reg_1299_pp0_iter19_reg);
    and_ln159_14_fu_1115_p2 <= (xor_ln159_8_fu_1110_p2 and or_ln159_3_fu_1096_p2);
    and_ln159_15_fu_1121_p2 <= (icmp_ln159_6_reg_1286_pp0_iter19_reg and and_ln159_14_fu_1115_p2);
    and_ln159_1_fu_825_p2 <= (xor_ln159_9_fu_769_p2 and icmp_ln159_9_fu_774_p2);
    and_ln159_4_fu_986_p2 <= (or_ln159_1_fu_982_p2 and Range2_all_ones_1_i_reg_1347);
    and_ln159_5_fu_997_p2 <= (carry_1_i_reg_1340 and Range1_all_ones_2_i_reg_1357);
    and_ln159_6_fu_1072_p2 <= (xor_ln159_6_fu_1067_p2 and or_ln159_2_fu_1061_p2);
    and_ln159_7_fu_1078_p2 <= (tmp_11_fu_964_p3 and deleted_ones_0_i_fu_1012_p2);
    and_ln159_8_fu_1090_p2 <= (xor_ln159_7_fu_1084_p2 and neg_src_0_i_fu_1030_p9);
    and_ln159_9_fu_752_p2 <= (xor_ln159_2_fu_747_p2 and icmp_ln159_1_reg_1251);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln151_fu_199_p2)
    begin
        if (((icmp_ln151_fu_199_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter19_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter19_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20)
    begin
        if (((ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_166, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_166;
        end if; 
    end process;

    ashr_ln159_fu_672_p2 <= std_logic_vector(shift_right(signed(select_ln159_reg_1244),to_integer(unsigned('0' & zext_ln159_2_fu_669_p1(31-1 downto 0)))));
    bitcast_ln157_fu_423_p1 <= xor_ln_fu_416_p3;
    bitcast_ln716_fu_434_p1 <= grp_fu_183_p1;
    carry_1_i_fu_763_p2 <= (xor_ln159_fu_741_p2 and and_ln159_10_fu_757_p2);
    cond193_i_fu_991_p3 <= 
        and_ln159_4_fu_986_p2 when (carry_1_i_reg_1340(0) = '1') else 
        Range1_all_ones_2_i_reg_1357;
    cond42_i_i_i_in_fu_329_p3 <= 
        lshr_ln138_fu_312_p2 when (icmp_ln138_1_fu_299_p2(0) = '1') else 
        shl_ln138_fu_324_p2;
    cond64_i_fu_710_p3 <= 
        tmp_5_reg_1218_pp0_iter18_reg when (icmp_ln159_4_reg_1276(0) = '1') else 
        tmp_7_reg_1281;
    deleted_ones_0_i_fu_1012_p2 <= (not_icmp_ln159_749_fu_1007_p2 or cond193_i_fu_991_p3);
    exp_x_fu_1133_p4 <= 
        ap_const_lv16_FFFF when (and_ln159_6_fu_1072_p2(0) = '1') else 
        ap_const_lv16_0;
    exp_x_fu_1133_p6 <= ref_tmp_i_i_fu_943_p9(16 - 1 downto 0);
    exp_x_fu_1133_p7 <= "XXXXXXXXXXXXXXXX";
    exp_x_fu_1133_p8 <= (icmp_ln159_reg_1238_pp0_iter19_reg & and_ln159_15_fu_1121_p2);
    icmp_ln138_1_fu_299_p2 <= "1" when (signed(add_ln138_fu_263_p2) > signed(ap_const_lv6_0)) else "0";
    icmp_ln138_fu_258_p2 <= "1" when (x_reg_1170 = ap_const_lv35_0) else "0";
    icmp_ln151_fu_199_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv11_400) else "0";
    icmp_ln159_10_fu_779_p2 <= "1" when (unsigned(add_ln159_5_reg_1291) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln159_11_fu_798_p2 <= "1" when (lshr_ln159_fu_787_p2 = lshr_ln159_1_fu_792_p2) else "0";
    icmp_ln159_12_fu_841_p2 <= "1" when (lshr_ln159_fu_787_p2 = ap_const_lv54_0) else "0";
    icmp_ln159_13_fu_853_p2 <= "1" when (add_ln159_5_reg_1291 = ap_const_lv12_36) else "0";
    icmp_ln159_14_fu_858_p2 <= "1" when (select_ln159_reg_1244 = ap_const_lv54_0) else "0";
    icmp_ln159_1_fu_505_p2 <= "1" when (signed(sub_ln159_1_fu_495_p2) > signed(ap_const_lv12_A)) else "0";
    icmp_ln159_2_fu_535_p2 <= "1" when (sub_ln159_1_fu_495_p2 = ap_const_lv12_A) else "0";
    icmp_ln159_3_fu_657_p2 <= "1" when (unsigned(select_ln159_1_reg_1256) < unsigned(ap_const_lv11_36)) else "0";
    icmp_ln159_4_fu_545_p2 <= "1" when (signed(add_ln159_fu_511_p2) > signed(ap_const_lv12_36)) else "0";
    icmp_ln159_5_fu_689_p2 <= "1" when (unsigned(select_ln159_1_reg_1256) < unsigned(ap_const_lv11_12)) else "0";
    icmp_ln159_6_fu_597_p2 <= "1" when (signed(tmp_10_fu_587_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln159_7_fu_619_p2 <= "1" when (signed(add_ln159_4_fu_603_p2) < signed(ap_const_lv12_36)) else "0";
    icmp_ln159_8_fu_633_p2 <= "1" when (unsigned(add_ln159_4_fu_603_p2) < unsigned(ap_const_lv12_36)) else "0";
    icmp_ln159_9_fu_774_p2 <= "1" when (signed(add_ln159_5_reg_1291) < signed(ap_const_lv12_36)) else "0";
    icmp_ln159_fu_462_p2 <= "1" when (trunc_ln159_fu_438_p1 = ap_const_lv63_0) else "0";
    lD_0_i_fu_647_p2 <= (tobool134_i_fu_639_p3 and icmp_ln159_8_fu_633_p2);
    lshr_ln138_1_fu_351_p4 <= add_ln138_2_fu_345_p2(35 downto 1);
    lshr_ln138_fu_312_p2 <= std_logic_vector(shift_right(unsigned(x_reg_1170),to_integer(unsigned('0' & zext_ln138_fu_308_p1(31-1 downto 0)))));
    lshr_ln159_1_fu_792_p2 <= std_logic_vector(shift_right(unsigned(ap_const_lv54_3FFFFFFFFFFFFF),to_integer(unsigned('0' & zext_ln159_6_fu_784_p1(31-1 downto 0)))));
    lshr_ln159_fu_787_p2 <= std_logic_vector(shift_right(unsigned(select_ln159_reg_1244),to_integer(unsigned('0' & zext_ln159_6_fu_784_p1(31-1 downto 0)))));
    neg_src_0_i_fu_1030_p2 <= (tmp_5_reg_1218_pp0_iter19_reg and tmp_11_fu_964_p3);
    neg_src_0_i_fu_1030_p4 <= (ap_const_lv1_1 xor and_ln159_5_fu_997_p2);
    neg_src_0_i_fu_1030_p7 <= "X";
    neg_src_0_i_fu_1030_p8 <= (not_icmp_ln159_749_fu_1007_p2 & and_ln159_12_fu_1018_p2);
    not_icmp_ln159_749_fu_1007_p2 <= (icmp_ln159_7_reg_1299_pp0_iter19_reg xor ap_const_lv1_1);
    or_ln159_1_fu_982_p2 <= (xor_ln159_1_reg_1352 or tmp_12_reg_1306_pp0_iter19_reg);
    or_ln159_2_fu_1061_p2 <= (tmp_11_fu_964_p3 or and_ln159_13_fu_1056_p2);
    or_ln159_3_fu_1096_p2 <= (and_ln159_8_fu_1090_p2 or and_ln159_6_fu_1072_p2);
    or_ln159_4_fu_569_p3 <= (ap_const_lv10_201 & icmp_ln159_1_fu_505_p2);
    or_ln159_5_fu_875_p2 <= (xor_ln159_11_fu_869_p2 or tmp_12_reg_1306);
    phi_ln138_1_fu_293_p2 <= (xor_ln138_fu_280_p2 and tmp_2_fu_286_p3);
    pi_assign_fu_400_p5 <= (zext_ln138_4_fu_361_p1(63 downto 32) & zext_ln138_5_fu_396_p1 & zext_ln138_4_fu_361_p1(22 downto 0));
    ref_tmp_i_i_fu_943_p7 <= "XXXXXXXXXXXXXXXXXX";
    ref_tmp_i_i_fu_943_p8 <= (icmp_ln159_2_reg_1264_pp0_iter19_reg & and_ln159_9_reg_1335);
    sel_tmp_fu_886_p3 <= (and_ln159_1_fu_825_p2 & and_ln159_11_fu_880_p2);
    select_ln138_fu_373_p3 <= 
        ap_const_lv8_7F when (tmp_3_fu_365_p3(0) = '1') else 
        ap_const_lv8_7E;
    select_ln159_1_fu_527_p3 <= 
        trunc_ln159_3_fu_517_p1 when (icmp_ln159_1_fu_505_p2(0) = '1') else 
        sub_ln159_2_fu_521_p2;
    select_ln159_1cast_fu_694_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln159_1_reg_1256),18));
    select_ln159_2_fu_681_p3 <= 
        trunc_ln159_5_fu_677_p1 when (icmp_ln159_3_fu_657_p2(0) = '1') else 
        select_ln159_5_fu_662_p3;
    select_ln159_3_fu_702_p3 <= 
        shl_ln159_fu_697_p2 when (icmp_ln159_5_fu_689_p2(0) = '1') else 
        ap_const_lv18_0;
    select_ln159_4_fu_977_p3 <= 
        Range1_all_ones_2_i_reg_1357 when (carry_1_i_reg_1340(0) = '1') else 
        Range1_all_zeros_2_i_reg_1364;
    select_ln159_5_fu_662_p3 <= 
        ap_const_lv18_3FFFF when (tmp_5_reg_1218_pp0_iter18_reg(0) = '1') else 
        ap_const_lv18_0;
    select_ln159_fu_488_p3 <= 
        sub_ln159_fu_482_p2 when (tmp_5_reg_1218(0) = '1') else 
        zext_ln159_1_fu_478_p1;
        sext_ln138_1_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln138_1_reg_1188),32));

        sext_ln138_2_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln138_1_reg_1193),32));

        sext_ln138_3_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln138_2_fu_381_p2),8));

        sext_ln159_1_fu_577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln159_4_fu_569_p3),12));

    shl_ln138_fu_324_p2 <= std_logic_vector(shift_left(unsigned(x_reg_1170),to_integer(unsigned('0' & zext_ln138_1_fu_320_p1(31-1 downto 0)))));
    shl_ln159_fu_697_p2 <= std_logic_vector(shift_left(unsigned(trunc_ln159_4_reg_1270),to_integer(unsigned('0' & select_ln159_1cast_fu_694_p1(18-1 downto 0)))));
    sub_ln138_1_fu_247_p2 <= std_logic_vector(unsigned(ap_const_lv6_19) - unsigned(sub_ln138_fu_235_p2));
    sub_ln138_2_fu_381_p2 <= std_logic_vector(unsigned(ap_const_lv6_F) - unsigned(trunc_ln138_reg_1178));
    sub_ln138_fu_235_p2 <= std_logic_vector(signed(ap_const_lv6_23) - signed(trunc_ln138_fu_231_p1));
    sub_ln159_1_fu_495_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(zext_ln159_fu_468_p1));
    sub_ln159_2_fu_521_p2 <= std_logic_vector(unsigned(ap_const_lv11_A) - unsigned(trunc_ln159_2_fu_501_p1));
    sub_ln159_fu_482_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(zext_ln159_1_fu_478_p1));
    table_out_address0 <= zext_ln151_fu_933_p1(10 - 1 downto 0);
    table_out_ce0 <= table_out_ce0_local;

    table_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter20 = ap_const_logic_1))) then 
            table_out_ce0_local <= ap_const_logic_1;
        else 
            table_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    table_out_d0 <= exp_x_fu_1133_p9;
    table_out_we0 <= table_out_we0_local;

    table_out_we0_local_assign_proc : process(ap_enable_reg_pp0_iter20, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter20 = ap_const_logic_1))) then 
            table_out_we0_local <= ap_const_logic_1;
        else 
            table_out_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_587_p4 <= add_ln159_3_fu_581_p2(11 downto 3);
    tmp_11_fu_964_p3 <= ref_tmp_i_i_fu_943_p9(17 downto 17);
    tmp_13_fu_804_p3 <= add_ln159_5_reg_1291(11 downto 11);
    tmp_1_fu_272_p3 <= add_ln138_fu_263_p2(5 downto 5);
        tmp_2_fu_286_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln138_fu_263_p2),32));

    tmp_3_fu_365_p3 <= add_ln138_2_fu_345_p2(25 downto 25);
    tmp_7_fu_561_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln159_1_fu_551_p2),32));
    tmp_8_fu_715_p3 <= select_ln159_2_fu_681_p3(17 downto 17);
    tmp_9_fu_733_p3 <= add_ln159_2_fu_727_p2(17 downto 17);
    tmp_fu_223_p1 <= (trunc_ln137_fu_211_p1 & ap_const_lv25_0);
        tobool134_i_fu_639_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln159_4_fu_603_p2),32));

    trunc_ln137_fu_211_p1 <= ap_sig_allocacmp_i_1(10 - 1 downto 0);
    trunc_ln138_fu_231_p1 <= tmp_fu_223_p3(6 - 1 downto 0);
    trunc_ln157_fu_412_p1 <= pi_assign_fu_400_p5(31 - 1 downto 0);
    trunc_ln159_1_fu_458_p1 <= bitcast_ln716_fu_434_p1(52 - 1 downto 0);
    trunc_ln159_2_fu_501_p1 <= sub_ln159_1_fu_495_p2(11 - 1 downto 0);
    trunc_ln159_3_fu_517_p1 <= add_ln159_fu_511_p2(11 - 1 downto 0);
    trunc_ln159_4_fu_541_p1 <= select_ln159_fu_488_p3(18 - 1 downto 0);
    trunc_ln159_5_fu_677_p1 <= ashr_ln159_fu_672_p2(18 - 1 downto 0);
    trunc_ln159_8_fu_653_p1 <= add_ln159_5_fu_613_p2(6 - 1 downto 0);
    trunc_ln159_fu_438_p1 <= bitcast_ln716_fu_434_p1(63 - 1 downto 0);
    x_2_fu_427_p3 <= 
        ap_const_lv32_80000000 when (icmp_ln138_reg_1198(0) = '1') else 
        bitcast_ln157_fu_423_p1;
    x_fu_215_p3 <= (trunc_ln137_fu_211_p1 & ap_const_lv25_0);
    xor_ln138_fu_280_p2 <= (tmp_1_fu_272_p3 xor ap_const_lv1_1);
    xor_ln159_10_fu_811_p2 <= (tmp_13_fu_804_p3 xor ap_const_lv1_1);
    xor_ln159_11_fu_869_p2 <= (icmp_ln159_9_fu_774_p2 xor ap_const_lv1_1);
    xor_ln159_1_fu_836_p2 <= (lD_0_i_reg_1313 xor ap_const_lv1_1);
    xor_ln159_2_fu_747_p2 <= (icmp_ln159_2_reg_1264 xor ap_const_lv1_1);
    xor_ln159_5_fu_1050_p2 <= (select_ln159_4_fu_977_p3 xor ap_const_lv1_1);
    xor_ln159_6_fu_1067_p2 <= (tmp_5_reg_1218_pp0_iter19_reg xor ap_const_lv1_1);
    xor_ln159_7_fu_1084_p2 <= (ap_const_lv1_1 xor and_ln159_7_fu_1078_p2);
    xor_ln159_8_fu_1110_p2 <= (icmp_ln159_reg_1238_pp0_iter19_reg xor ap_const_lv1_1);
    xor_ln159_9_fu_769_p2 <= (tmp_12_reg_1306 xor ap_const_lv1_1);
    xor_ln159_fu_741_p2 <= (tmp_9_fu_733_p3 xor ap_const_lv1_1);
    xor_ln_fu_416_p3 <= (ap_const_lv1_1 & trunc_ln157_reg_1203);
    zext_ln138_1_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln138_2_fu_317_p1),35));
    zext_ln138_2_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cond42_i_i_i_in_fu_329_p3),36));
    zext_ln138_3_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phi_ln138_1_fu_293_p2),36));
    zext_ln138_4_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln138_1_fu_351_p4),64));
    zext_ln138_5_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln138_3_fu_390_p2),9));
    zext_ln138_fu_308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln138_1_fu_305_p1),35));
    zext_ln151_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_1_reg_1161_pp0_iter19_reg),64));
    zext_ln159_1_cast_fu_471_p3 <= (ap_const_lv1_1 & trunc_ln159_1_reg_1233);
    zext_ln159_1_fu_478_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln159_1_cast_fu_471_p3),54));
    zext_ln159_2_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln159_1_reg_1256),54));
    zext_ln159_3_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cond64_i_fu_710_p3),18));
    zext_ln159_6_fu_784_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln159_8_reg_1320),54));
    zext_ln159_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_reg_1228),12));
end behav;
