-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC );
end;


architecture behav of myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 : STD_LOGIC;
    signal void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_pooling2d_cl_stdEe IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_pooling2d_cl_stdEe
    generic map (
        DataWidth => 16,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_5,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0,
        d0 => p_read,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_pooling2d_cl_stdEe
    generic map (
        DataWidth => 16,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_5,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0,
        d0 => p_read1,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_pooling2d_cl_stdEe
    generic map (
        DataWidth => 16,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_5,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0,
        d0 => p_read2,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0);

    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_U : component myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_pooling2d_cl_stdEe
    generic map (
        DataWidth => 16,
        AddressRange => 6,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => ap_const_lv3_5,
        ce0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0,
        we0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0,
        d0 => p_read3,
        q0 => void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_ce)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_ce)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_const_logic_0 = ap_ce))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_assign_proc : process(ap_CS_fsm_state1, p_read2, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o <= p_read2;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_assign_proc : process(ap_CS_fsm_state1, p_read1, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o <= p_read1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_assign_proc : process(ap_CS_fsm_state1, p_read, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o <= p_read;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_assign_proc : process(ap_CS_fsm_state1, p_read3, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o <= p_read3;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i;
        end if; 
    end process;


    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld <= ap_const_logic_1;
        else 
            p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_assign_proc : process(ap_CS_fsm_state1, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i, void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_assign_proc : process(ap_CS_fsm_state1, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i, void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_assign_proc : process(ap_CS_fsm_state1, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i, void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_i;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_assign_proc : process(ap_CS_fsm_state1, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i, void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o <= void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;
        end if; 
    end process;


    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld <= ap_const_logic_1;
        else 
            void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_ce)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_ce))) then 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 <= ap_const_logic_1;
        else 
            void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
