# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.srcs/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3.xci
# IP: The module: 'bd_smoke_rst_ps8_0_177M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.srcs/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3.xci
# IP: The module: 'bd_smoke_rst_ps8_0_177M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/OmilosNeonTexn/Desktop/fpga_cnn_hls4ml/hls_smoke/project_1/project_1.gen/sources_1/bd/bd_smoke/ip/bd_smoke_rst_ps8_0_177M_3/bd_smoke_rst_ps8_0_177M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_smoke_rst_ps8_0_177M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
