-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer6_out_dout : IN STD_LOGIC_VECTOR (311 downto 0);
    layer6_out_empty_n : IN STD_LOGIC;
    layer6_out_read : OUT STD_LOGIC;
    layer6_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer6_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    layer7_out_full_n : IN STD_LOGIC;
    layer7_out_write : OUT STD_LOGIC;
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_4D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001101";
    constant ap_const_lv32_4E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001110";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv32_9B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011011";
    constant ap_const_lv32_9C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011100";
    constant ap_const_lv32_C2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000010";
    constant ap_const_lv32_C3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000011";
    constant ap_const_lv32_E9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101001";
    constant ap_const_lv32_EA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101010";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_111 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010001";
    constant ap_const_lv32_137 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110111";
    constant ap_const_lv39_0 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_67 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100111";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_A6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100110";
    constant ap_const_lv32_B5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110101";
    constant ap_const_lv32_CD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001101";
    constant ap_const_lv32_DC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011100";
    constant ap_const_lv32_F4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110100";
    constant ap_const_lv32_103 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000011";
    constant ap_const_lv32_11B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011011";
    constant ap_const_lv32_12A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer6_out_blk_n : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal select_ln51_fu_191_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_reg_380 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal select_ln51_1_fu_215_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_1_reg_385 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_2_fu_239_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_2_reg_390 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_3_fu_263_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_3_reg_395 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_4_fu_287_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_4_reg_400 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_5_fu_311_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_5_reg_405 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_6_fu_335_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_6_reg_410 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_7_fu_359_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln51_7_reg_415 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_fu_101_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln3_fu_181_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_1_fu_105_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_1_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_1_fu_205_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_2_fu_115_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_2_fu_223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_2_fu_229_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_3_fu_125_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_3_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_3_fu_253_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_4_fu_135_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_4_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_4_fu_277_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_5_fu_145_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_5_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_5_fu_301_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_6_fu_155_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_6_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_6_fu_325_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln44_7_fu_165_p4 : STD_LOGIC_VECTOR (38 downto 0);
    signal icmp_ln51_7_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_7_fu_349_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                select_ln51_1_reg_385 <= select_ln51_1_fu_215_p3;
                select_ln51_2_reg_390 <= select_ln51_2_fu_239_p3;
                select_ln51_3_reg_395 <= select_ln51_3_fu_263_p3;
                select_ln51_4_reg_400 <= select_ln51_4_fu_287_p3;
                select_ln51_5_reg_405 <= select_ln51_5_fu_311_p3;
                select_ln51_6_reg_410 <= select_ln51_6_fu_335_p3;
                select_ln51_7_reg_415 <= select_ln51_7_fu_359_p3;
                select_ln51_reg_380 <= select_ln51_fu_191_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer7_out_full_n, ap_CS_fsm_state2, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(layer7_out_full_n)
    begin
        if ((layer7_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer6_out_empty_n)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (layer6_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer7_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    icmp_ln51_1_fu_199_p2 <= "1" when (signed(trunc_ln44_1_fu_105_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_2_fu_223_p2 <= "1" when (signed(trunc_ln44_2_fu_115_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_3_fu_247_p2 <= "1" when (signed(trunc_ln44_3_fu_125_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_4_fu_271_p2 <= "1" when (signed(trunc_ln44_4_fu_135_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_5_fu_295_p2 <= "1" when (signed(trunc_ln44_5_fu_145_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_6_fu_319_p2 <= "1" when (signed(trunc_ln44_6_fu_155_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_7_fu_343_p2 <= "1" when (signed(trunc_ln44_7_fu_165_p4) > signed(ap_const_lv39_0)) else "0";
    icmp_ln51_fu_175_p2 <= "1" when (signed(trunc_ln44_fu_101_p1) > signed(ap_const_lv39_0)) else "0";

    internal_ap_ready_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer6_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer6_out_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_blk_n <= layer6_out_empty_n;
        else 
            layer6_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer6_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer6_out_read <= ap_const_logic_1;
        else 
            layer6_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_blk_n_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            layer7_out_blk_n <= layer7_out_full_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer7_out_din <= (((((((select_ln51_7_reg_415 & select_ln51_6_reg_410) & select_ln51_5_reg_405) & select_ln51_4_reg_400) & select_ln51_3_reg_395) & select_ln51_2_reg_390) & select_ln51_1_reg_385) & select_ln51_reg_380);

    layer7_out_write_assign_proc : process(layer7_out_full_n, ap_CS_fsm_state2)
    begin
        if (((layer7_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            layer7_out_write <= ap_const_logic_1;
        else 
            layer7_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_1_fu_215_p3 <= 
        trunc_ln52_1_fu_205_p4 when (icmp_ln51_1_fu_199_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_2_fu_239_p3 <= 
        trunc_ln52_2_fu_229_p4 when (icmp_ln51_2_fu_223_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_3_fu_263_p3 <= 
        trunc_ln52_3_fu_253_p4 when (icmp_ln51_3_fu_247_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_4_fu_287_p3 <= 
        trunc_ln52_4_fu_277_p4 when (icmp_ln51_4_fu_271_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_5_fu_311_p3 <= 
        trunc_ln52_5_fu_301_p4 when (icmp_ln51_5_fu_295_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_6_fu_335_p3 <= 
        trunc_ln52_6_fu_325_p4 when (icmp_ln51_6_fu_319_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_7_fu_359_p3 <= 
        trunc_ln52_7_fu_349_p4 when (icmp_ln51_7_fu_343_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln51_fu_191_p3 <= 
        trunc_ln3_fu_181_p4 when (icmp_ln51_fu_175_p2(0) = '1') else 
        ap_const_lv16_0;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln3_fu_181_p4 <= layer6_out_dout(25 downto 10);
    trunc_ln44_1_fu_105_p4 <= layer6_out_dout(77 downto 39);
    trunc_ln44_2_fu_115_p4 <= layer6_out_dout(116 downto 78);
    trunc_ln44_3_fu_125_p4 <= layer6_out_dout(155 downto 117);
    trunc_ln44_4_fu_135_p4 <= layer6_out_dout(194 downto 156);
    trunc_ln44_5_fu_145_p4 <= layer6_out_dout(233 downto 195);
    trunc_ln44_6_fu_155_p4 <= layer6_out_dout(272 downto 234);
    trunc_ln44_7_fu_165_p4 <= layer6_out_dout(311 downto 273);
    trunc_ln44_fu_101_p1 <= layer6_out_dout(39 - 1 downto 0);
    trunc_ln52_1_fu_205_p4 <= layer6_out_dout(64 downto 49);
    trunc_ln52_2_fu_229_p4 <= layer6_out_dout(103 downto 88);
    trunc_ln52_3_fu_253_p4 <= layer6_out_dout(142 downto 127);
    trunc_ln52_4_fu_277_p4 <= layer6_out_dout(181 downto 166);
    trunc_ln52_5_fu_301_p4 <= layer6_out_dout(220 downto 205);
    trunc_ln52_6_fu_325_p4 <= layer6_out_dout(259 downto 244);
    trunc_ln52_7_fu_349_p4 <= layer6_out_dout(298 downto 283);
end behav;
