-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_array_ap_fixed_8u_array_ap_fixed_36_16_5_3_0_2u_config8_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    layer7_out_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    layer7_out_empty_n : IN STD_LOGIC;
    layer7_out_read : OUT STD_LOGIC;
    layer7_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer7_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_din : OUT STD_LOGIC_VECTOR (71 downto 0);
    layer8_out_full_n : IN STD_LOGIC;
    layer8_out_write : OUT STD_LOGIC;
    layer8_out_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    layer8_out_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of myproject_dense_array_ap_fixed_8u_array_ap_fixed_36_16_5_3_0_2u_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal layer7_out_blk_n : STD_LOGIC;
    signal layer8_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal data_fu_77_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_reg_166 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal data_1_reg_171 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_2_reg_176 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_3_reg_181 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_4_reg_186 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_5_reg_191 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_6_reg_196 : STD_LOGIC_VECTOR (15 downto 0);
    signal data_7_reg_201 : STD_LOGIC_VECTOR (15 downto 0);
    signal res_reg_206 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal res_1_reg_211 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_done : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_idle : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready : STD_LOGIC;
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1 : STD_LOGIC_VECTOR (35 downto 0);
    signal grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_val1 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_1_val2 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_2_val3 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_3_val4 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_4_val5 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_5_val6 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_6_val7 : IN STD_LOGIC_VECTOR (15 downto 0);
        data_7_val8 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (35 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (35 downto 0) );
    end component;



begin
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65 : component myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start,
        ap_done => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_done,
        ap_idle => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_idle,
        ap_ready => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready,
        data_0_val1 => data_reg_166,
        data_1_val2 => data_1_reg_171,
        data_2_val3 => data_2_reg_176,
        data_3_val4 => data_3_reg_181,
        data_4_val5 => data_4_reg_186,
        data_5_val6 => data_5_reg_191,
        data_6_val7 => data_6_reg_196,
        data_7_val8 => data_7_reg_201,
        ap_return_0 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0,
        ap_return_1 => grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_logic_1 = ap_NS_fsm_state2))) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_ready = ap_const_logic_1)) then 
                    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_1_reg_171 <= layer7_out_dout(31 downto 16);
                data_2_reg_176 <= layer7_out_dout(47 downto 32);
                data_3_reg_181 <= layer7_out_dout(63 downto 48);
                data_4_reg_186 <= layer7_out_dout(79 downto 64);
                data_5_reg_191 <= layer7_out_dout(95 downto 80);
                data_6_reg_196 <= layer7_out_dout(111 downto 96);
                data_7_reg_201 <= layer7_out_dout(127 downto 112);
                data_reg_166 <= data_fu_77_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                res_1_reg_211 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_1;
                res_reg_206 <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, layer8_out_full_n, ap_CS_fsm_state4, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(layer8_out_full_n)
    begin
        if ((layer8_out_full_n = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, layer7_out_empty_n)
    begin
                ap_block_state1 <= ((layer7_out_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, layer8_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    data_fu_77_p1 <= layer7_out_dout(16 - 1 downto 0);
    grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start <= grp_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s_fu_65_ap_start_reg;

    internal_ap_ready_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    layer7_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, layer7_out_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_blk_n <= layer7_out_empty_n;
        else 
            layer7_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer7_out_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            layer7_out_read <= ap_const_logic_1;
        else 
            layer7_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer8_out_blk_n_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            layer8_out_blk_n <= layer8_out_full_n;
        else 
            layer8_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer8_out_din <= (res_1_reg_211 & res_reg_206);

    layer8_out_write_assign_proc : process(layer8_out_full_n, ap_CS_fsm_state4)
    begin
        if (((layer8_out_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            layer8_out_write <= ap_const_logic_1;
        else 
            layer8_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
