// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_array_ap_fixed_39_19_5_3_0_8u_config6_Pipeline_DataPrepare (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer4_out_dout,
        layer4_out_empty_n,
        layer4_out_read,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        data_42_out,
        data_42_out_ap_vld,
        data_41_out,
        data_41_out_ap_vld,
        data_40_out,
        data_40_out_ap_vld,
        data_39_out,
        data_39_out_ap_vld,
        data_38_out,
        data_38_out_ap_vld,
        data_37_out,
        data_37_out_ap_vld,
        data_36_out,
        data_36_out_ap_vld,
        data_35_out,
        data_35_out_ap_vld,
        data_34_out,
        data_34_out_ap_vld,
        data_33_out,
        data_33_out_ap_vld,
        data_32_out,
        data_32_out_ap_vld,
        data_31_out,
        data_31_out_ap_vld,
        data_30_out,
        data_30_out_ap_vld,
        data_29_out,
        data_29_out_ap_vld,
        data_28_out,
        data_28_out_ap_vld,
        data_27_out,
        data_27_out_ap_vld,
        data_26_out,
        data_26_out_ap_vld,
        data_25_out,
        data_25_out_ap_vld,
        data_24_out,
        data_24_out_ap_vld,
        data_23_out,
        data_23_out_ap_vld,
        data_22_out,
        data_22_out_ap_vld,
        data_21_out,
        data_21_out_ap_vld,
        data_20_out,
        data_20_out_ap_vld,
        data_19_out,
        data_19_out_ap_vld,
        data_18_out,
        data_18_out_ap_vld,
        data_17_out,
        data_17_out_ap_vld,
        data_16_out,
        data_16_out_ap_vld,
        data_15_out,
        data_15_out_ap_vld,
        data_14_out,
        data_14_out_ap_vld,
        data_13_out,
        data_13_out_ap_vld,
        data_12_out,
        data_12_out_ap_vld,
        data_11_out,
        data_11_out_ap_vld,
        data_10_out,
        data_10_out_ap_vld,
        data_9_out,
        data_9_out_ap_vld,
        data_8_out,
        data_8_out_ap_vld,
        data_out,
        data_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] layer4_out_dout;
input   layer4_out_empty_n;
output   layer4_out_read;
input  [4:0] layer4_out_num_data_valid;
input  [4:0] layer4_out_fifo_cap;
output  [15:0] data_42_out;
output   data_42_out_ap_vld;
output  [15:0] data_41_out;
output   data_41_out_ap_vld;
output  [15:0] data_40_out;
output   data_40_out_ap_vld;
output  [15:0] data_39_out;
output   data_39_out_ap_vld;
output  [15:0] data_38_out;
output   data_38_out_ap_vld;
output  [15:0] data_37_out;
output   data_37_out_ap_vld;
output  [15:0] data_36_out;
output   data_36_out_ap_vld;
output  [15:0] data_35_out;
output   data_35_out_ap_vld;
output  [15:0] data_34_out;
output   data_34_out_ap_vld;
output  [15:0] data_33_out;
output   data_33_out_ap_vld;
output  [15:0] data_32_out;
output   data_32_out_ap_vld;
output  [15:0] data_31_out;
output   data_31_out_ap_vld;
output  [15:0] data_30_out;
output   data_30_out_ap_vld;
output  [15:0] data_29_out;
output   data_29_out_ap_vld;
output  [15:0] data_28_out;
output   data_28_out_ap_vld;
output  [15:0] data_27_out;
output   data_27_out_ap_vld;
output  [15:0] data_26_out;
output   data_26_out_ap_vld;
output  [15:0] data_25_out;
output   data_25_out_ap_vld;
output  [15:0] data_24_out;
output   data_24_out_ap_vld;
output  [15:0] data_23_out;
output   data_23_out_ap_vld;
output  [15:0] data_22_out;
output   data_22_out_ap_vld;
output  [15:0] data_21_out;
output   data_21_out_ap_vld;
output  [15:0] data_20_out;
output   data_20_out_ap_vld;
output  [15:0] data_19_out;
output   data_19_out_ap_vld;
output  [15:0] data_18_out;
output   data_18_out_ap_vld;
output  [15:0] data_17_out;
output   data_17_out_ap_vld;
output  [15:0] data_16_out;
output   data_16_out_ap_vld;
output  [15:0] data_15_out;
output   data_15_out_ap_vld;
output  [15:0] data_14_out;
output   data_14_out_ap_vld;
output  [15:0] data_13_out;
output   data_13_out_ap_vld;
output  [15:0] data_12_out;
output   data_12_out_ap_vld;
output  [15:0] data_11_out;
output   data_11_out_ap_vld;
output  [15:0] data_10_out;
output   data_10_out_ap_vld;
output  [15:0] data_9_out;
output   data_9_out_ap_vld;
output  [15:0] data_8_out;
output   data_8_out_ap_vld;
output  [15:0] data_out;
output   data_out_ap_vld;

reg ap_idle;
reg layer4_out_read;
reg data_42_out_ap_vld;
reg data_41_out_ap_vld;
reg data_40_out_ap_vld;
reg data_39_out_ap_vld;
reg data_38_out_ap_vld;
reg data_37_out_ap_vld;
reg data_36_out_ap_vld;
reg data_35_out_ap_vld;
reg data_34_out_ap_vld;
reg data_33_out_ap_vld;
reg data_32_out_ap_vld;
reg data_31_out_ap_vld;
reg data_30_out_ap_vld;
reg data_29_out_ap_vld;
reg data_28_out_ap_vld;
reg data_27_out_ap_vld;
reg data_26_out_ap_vld;
reg data_25_out_ap_vld;
reg data_24_out_ap_vld;
reg data_23_out_ap_vld;
reg data_22_out_ap_vld;
reg data_21_out_ap_vld;
reg data_20_out_ap_vld;
reg data_19_out_ap_vld;
reg data_18_out_ap_vld;
reg data_17_out_ap_vld;
reg data_16_out_ap_vld;
reg data_15_out_ap_vld;
reg data_14_out_ap_vld;
reg data_13_out_ap_vld;
reg data_12_out_ap_vld;
reg data_11_out_ap_vld;
reg data_10_out_ap_vld;
reg data_9_out_ap_vld;
reg data_8_out_ap_vld;
reg data_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln33_fu_766_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer4_out_blk_n;
reg   [3:0] i_in73_fu_132;
wire   [3:0] i_in_fu_580_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_in73_load;
wire   [3:0] i_in73_load_load_fu_543_p1;
reg   [15:0] p_0_3_0_0_0712_fu_136;
reg   [15:0] p_0_2_0_0_0694_fu_140;
reg   [15:0] p_0_1_0_0_0676_fu_144;
reg   [15:0] p_0_0_0_0_0658_fu_148;
wire   [15:0] data_pack_fu_546_p1;
reg   [15:0] p_0_3_0_0_06310_fu_152;
reg   [15:0] p_0_2_0_0_06112_fu_156;
reg   [15:0] p_0_1_0_0_05914_fu_160;
reg   [15:0] p_0_0_0_0_05716_fu_164;
reg   [15:0] p_0_3_0_0_05518_fu_168;
reg   [15:0] p_0_2_0_0_05320_fu_172;
reg   [15:0] p_0_1_0_0_05122_fu_176;
reg   [15:0] p_0_0_0_0_04924_fu_180;
reg   [15:0] p_0_3_0_0_04726_fu_184;
reg   [15:0] p_0_2_0_0_04528_fu_188;
reg   [15:0] p_0_1_0_0_04330_fu_192;
reg   [15:0] p_0_0_0_0_04132_fu_196;
reg   [15:0] p_0_3_0_0_03934_fu_200;
reg   [15:0] p_0_2_0_0_03736_fu_204;
reg   [15:0] p_0_1_0_0_03538_fu_208;
reg   [15:0] p_0_0_0_0_03340_fu_212;
reg   [15:0] p_0_3_0_0_03142_fu_216;
reg   [15:0] p_0_2_0_0_02944_fu_220;
reg   [15:0] p_0_1_0_0_02746_fu_224;
reg   [15:0] p_0_0_0_0_02548_fu_228;
reg   [15:0] p_0_3_0_0_02350_fu_232;
reg   [15:0] p_0_2_0_0_02152_fu_236;
reg   [15:0] p_0_1_0_0_01954_fu_240;
reg   [15:0] p_0_0_0_0_01756_fu_244;
reg   [15:0] p_0_3_0_0_01558_fu_248;
reg   [15:0] p_0_2_0_0_01360_fu_252;
reg   [15:0] p_0_1_0_0_01162_fu_256;
reg   [15:0] p_0_0_0_0_0964_fu_260;
reg   [15:0] p_0_3_0_0_0766_fu_264;
reg   [15:0] p_0_2_0_0_0568_fu_268;
reg   [15:0] p_0_1_0_0_0370_fu_272;
reg   [15:0] p_0_0_0_0_0172_fu_276;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_in73_fu_132 = 4'd0;
#0 p_0_3_0_0_0712_fu_136 = 16'd0;
#0 p_0_2_0_0_0694_fu_140 = 16'd0;
#0 p_0_1_0_0_0676_fu_144 = 16'd0;
#0 p_0_0_0_0_0658_fu_148 = 16'd0;
#0 p_0_3_0_0_06310_fu_152 = 16'd0;
#0 p_0_2_0_0_06112_fu_156 = 16'd0;
#0 p_0_1_0_0_05914_fu_160 = 16'd0;
#0 p_0_0_0_0_05716_fu_164 = 16'd0;
#0 p_0_3_0_0_05518_fu_168 = 16'd0;
#0 p_0_2_0_0_05320_fu_172 = 16'd0;
#0 p_0_1_0_0_05122_fu_176 = 16'd0;
#0 p_0_0_0_0_04924_fu_180 = 16'd0;
#0 p_0_3_0_0_04726_fu_184 = 16'd0;
#0 p_0_2_0_0_04528_fu_188 = 16'd0;
#0 p_0_1_0_0_04330_fu_192 = 16'd0;
#0 p_0_0_0_0_04132_fu_196 = 16'd0;
#0 p_0_3_0_0_03934_fu_200 = 16'd0;
#0 p_0_2_0_0_03736_fu_204 = 16'd0;
#0 p_0_1_0_0_03538_fu_208 = 16'd0;
#0 p_0_0_0_0_03340_fu_212 = 16'd0;
#0 p_0_3_0_0_03142_fu_216 = 16'd0;
#0 p_0_2_0_0_02944_fu_220 = 16'd0;
#0 p_0_1_0_0_02746_fu_224 = 16'd0;
#0 p_0_0_0_0_02548_fu_228 = 16'd0;
#0 p_0_3_0_0_02350_fu_232 = 16'd0;
#0 p_0_2_0_0_02152_fu_236 = 16'd0;
#0 p_0_1_0_0_01954_fu_240 = 16'd0;
#0 p_0_0_0_0_01756_fu_244 = 16'd0;
#0 p_0_3_0_0_01558_fu_248 = 16'd0;
#0 p_0_2_0_0_01360_fu_252 = 16'd0;
#0 p_0_1_0_0_01162_fu_256 = 16'd0;
#0 p_0_0_0_0_0964_fu_260 = 16'd0;
#0 p_0_3_0_0_0766_fu_264 = 16'd0;
#0 p_0_2_0_0_0568_fu_268 = 16'd0;
#0 p_0_1_0_0_0370_fu_272 = 16'd0;
#0 p_0_0_0_0_0172_fu_276 = 16'd0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        i_in73_fu_132 <= i_in_fu_580_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd7))) begin
        p_0_0_0_0_0172_fu_276 <= data_pack_fu_546_p1;
        p_0_1_0_0_0370_fu_272 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_0568_fu_268 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_0766_fu_264 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd5))) begin
        p_0_0_0_0_01756_fu_244 <= data_pack_fu_546_p1;
        p_0_1_0_0_01954_fu_240 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_02152_fu_236 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_02350_fu_232 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd4))) begin
        p_0_0_0_0_02548_fu_228 <= data_pack_fu_546_p1;
        p_0_1_0_0_02746_fu_224 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_02944_fu_220 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_03142_fu_216 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd3))) begin
        p_0_0_0_0_03340_fu_212 <= data_pack_fu_546_p1;
        p_0_1_0_0_03538_fu_208 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_03736_fu_204 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_03934_fu_200 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd2))) begin
        p_0_0_0_0_04132_fu_196 <= data_pack_fu_546_p1;
        p_0_1_0_0_04330_fu_192 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_04528_fu_188 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_04726_fu_184 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd1))) begin
        p_0_0_0_0_04924_fu_180 <= data_pack_fu_546_p1;
        p_0_1_0_0_05122_fu_176 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_05320_fu_172 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_05518_fu_168 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd0))) begin
        p_0_0_0_0_05716_fu_164 <= data_pack_fu_546_p1;
        p_0_1_0_0_05914_fu_160 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_06112_fu_156 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_06310_fu_152 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((~(i_in73_load_load_fu_543_p1 == 4'd7) & ~(i_in73_load_load_fu_543_p1 == 4'd6) & ~(i_in73_load_load_fu_543_p1 == 4'd5) & ~(i_in73_load_load_fu_543_p1 == 4'd4) & ~(i_in73_load_load_fu_543_p1 == 4'd3) & ~(i_in73_load_load_fu_543_p1 == 4'd2) & ~(i_in73_load_load_fu_543_p1 == 4'd1) & ~(i_in73_load_load_fu_543_p1 == 4'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_0_0_0_0_0658_fu_148 <= data_pack_fu_546_p1;
        p_0_1_0_0_0676_fu_144 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_0694_fu_140 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_0712_fu_136 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (i_in73_load_load_fu_543_p1 == 4'd6))) begin
        p_0_0_0_0_0964_fu_260 <= data_pack_fu_546_p1;
        p_0_1_0_0_01162_fu_256 <= {{layer4_out_dout[31:16]}};
        p_0_2_0_0_01360_fu_252 <= {{layer4_out_dout[47:32]}};
        p_0_3_0_0_01558_fu_248 <= {{layer4_out_dout[63:48]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_in73_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_in73_load = i_in73_fu_132;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_10_out_ap_vld = 1'b1;
    end else begin
        data_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_11_out_ap_vld = 1'b1;
    end else begin
        data_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_12_out_ap_vld = 1'b1;
    end else begin
        data_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_13_out_ap_vld = 1'b1;
    end else begin
        data_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_14_out_ap_vld = 1'b1;
    end else begin
        data_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_15_out_ap_vld = 1'b1;
    end else begin
        data_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_16_out_ap_vld = 1'b1;
    end else begin
        data_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_17_out_ap_vld = 1'b1;
    end else begin
        data_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_18_out_ap_vld = 1'b1;
    end else begin
        data_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_19_out_ap_vld = 1'b1;
    end else begin
        data_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_20_out_ap_vld = 1'b1;
    end else begin
        data_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_21_out_ap_vld = 1'b1;
    end else begin
        data_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_22_out_ap_vld = 1'b1;
    end else begin
        data_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_23_out_ap_vld = 1'b1;
    end else begin
        data_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_24_out_ap_vld = 1'b1;
    end else begin
        data_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_25_out_ap_vld = 1'b1;
    end else begin
        data_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_26_out_ap_vld = 1'b1;
    end else begin
        data_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_27_out_ap_vld = 1'b1;
    end else begin
        data_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_28_out_ap_vld = 1'b1;
    end else begin
        data_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_29_out_ap_vld = 1'b1;
    end else begin
        data_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_30_out_ap_vld = 1'b1;
    end else begin
        data_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_31_out_ap_vld = 1'b1;
    end else begin
        data_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_32_out_ap_vld = 1'b1;
    end else begin
        data_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_33_out_ap_vld = 1'b1;
    end else begin
        data_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_34_out_ap_vld = 1'b1;
    end else begin
        data_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_35_out_ap_vld = 1'b1;
    end else begin
        data_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_36_out_ap_vld = 1'b1;
    end else begin
        data_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_37_out_ap_vld = 1'b1;
    end else begin
        data_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_38_out_ap_vld = 1'b1;
    end else begin
        data_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_39_out_ap_vld = 1'b1;
    end else begin
        data_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_40_out_ap_vld = 1'b1;
    end else begin
        data_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_41_out_ap_vld = 1'b1;
    end else begin
        data_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_42_out_ap_vld = 1'b1;
    end else begin
        data_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_8_out_ap_vld = 1'b1;
    end else begin
        data_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_9_out_ap_vld = 1'b1;
    end else begin
        data_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln33_fu_766_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        data_out_ap_vld = 1'b1;
    end else begin
        data_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (layer4_out_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign data_10_out = p_0_3_0_0_0766_fu_264;

assign data_11_out = p_0_0_0_0_0964_fu_260;

assign data_12_out = p_0_1_0_0_01162_fu_256;

assign data_13_out = p_0_2_0_0_01360_fu_252;

assign data_14_out = p_0_3_0_0_01558_fu_248;

assign data_15_out = p_0_0_0_0_01756_fu_244;

assign data_16_out = p_0_1_0_0_01954_fu_240;

assign data_17_out = p_0_2_0_0_02152_fu_236;

assign data_18_out = p_0_3_0_0_02350_fu_232;

assign data_19_out = p_0_0_0_0_02548_fu_228;

assign data_20_out = p_0_1_0_0_02746_fu_224;

assign data_21_out = p_0_2_0_0_02944_fu_220;

assign data_22_out = p_0_3_0_0_03142_fu_216;

assign data_23_out = p_0_0_0_0_03340_fu_212;

assign data_24_out = p_0_1_0_0_03538_fu_208;

assign data_25_out = p_0_2_0_0_03736_fu_204;

assign data_26_out = p_0_3_0_0_03934_fu_200;

assign data_27_out = p_0_0_0_0_04132_fu_196;

assign data_28_out = p_0_1_0_0_04330_fu_192;

assign data_29_out = p_0_2_0_0_04528_fu_188;

assign data_30_out = p_0_3_0_0_04726_fu_184;

assign data_31_out = p_0_0_0_0_04924_fu_180;

assign data_32_out = p_0_1_0_0_05122_fu_176;

assign data_33_out = p_0_2_0_0_05320_fu_172;

assign data_34_out = p_0_3_0_0_05518_fu_168;

assign data_35_out = p_0_0_0_0_05716_fu_164;

assign data_36_out = p_0_1_0_0_05914_fu_160;

assign data_37_out = p_0_2_0_0_06112_fu_156;

assign data_38_out = p_0_3_0_0_06310_fu_152;

assign data_39_out = p_0_0_0_0_0658_fu_148;

assign data_40_out = p_0_1_0_0_0676_fu_144;

assign data_41_out = p_0_2_0_0_0694_fu_140;

assign data_42_out = p_0_3_0_0_0712_fu_136;

assign data_8_out = p_0_1_0_0_0370_fu_272;

assign data_9_out = p_0_2_0_0_0568_fu_268;

assign data_out = p_0_0_0_0_0172_fu_276;

assign data_pack_fu_546_p1 = layer4_out_dout[15:0];

assign i_in73_load_load_fu_543_p1 = ap_sig_allocacmp_i_in73_load;

assign i_in_fu_580_p2 = (ap_sig_allocacmp_i_in73_load + 4'd1);

assign icmp_ln33_fu_766_p2 = ((ap_sig_allocacmp_i_in73_load == 4'd8) ? 1'b1 : 1'b0);

endmodule //myproject_dense_array_array_ap_fixed_39_19_5_3_0_8u_config6_Pipeline_DataPrepare
