// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_2u_softmax_config9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer8_out_dout,
        layer8_out_empty_n,
        layer8_out_read,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer9_out_TDATA,
        layer9_out_TVALID,
        layer9_out_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [71:0] layer8_out_dout;
input   layer8_out_empty_n;
output   layer8_out_read;
input  [1:0] layer8_out_num_data_valid;
input  [1:0] layer8_out_fifo_cap;
output  [31:0] layer9_out_TDATA;
output   layer9_out_TVALID;
input   layer9_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer8_out_read;
reg layer9_out_TVALID;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] invert_table_address0;
wire   [17:0] invert_table_q0;
reg    layer8_out_blk_n;
wire    ap_CS_fsm_state2;
reg    layer9_out_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln66_fu_174_p2;
reg   [0:0] icmp_ln66_reg_312;
wire   [34:0] trunc_ln66_fu_180_p1;
reg   [34:0] trunc_ln66_reg_317;
reg   [34:0] tmp_reg_323;
wire    ap_CS_fsm_state3;
reg  signed [15:0] a_reg_339;
wire    ap_CS_fsm_state4;
reg  signed [15:0] b_reg_344;
reg   [17:0] inv_exp_sum_reg_354;
wire    ap_CS_fsm_state5;
reg   [9:0] exp_table_address0;
reg    exp_table_ce0;
reg    exp_table_we0;
wire   [15:0] exp_table_q0;
wire   [9:0] exp_table_address1;
wire   [15:0] exp_table_q1;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_done;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_idle;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_ready;
wire   [9:0] grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_address0;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_ce0;
wire    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_we0;
wire   [15:0] grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_d0;
reg    grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg;
wire   [63:0] zext_ln223_fu_225_p1;
wire   [63:0] zext_ln223_1_fu_240_p1;
wire   [63:0] zext_ln232_fu_265_p1;
reg    exp_table_ce1_local;
reg    exp_table_ce0_local;
reg    invert_table_ce0_local;
wire  signed [17:0] mul_ln241_fu_127_p0;
wire  signed [25:0] sext_ln241_fu_270_p1;
wire  signed [17:0] mul_ln241_1_fu_128_p0;
wire   [35:0] trunc_ln198_fu_160_p1;
wire   [35:0] trunc_ln198_1_fu_164_p4;
wire   [0:0] xor_ln66_fu_194_p2;
wire   [34:0] select_ln66_fu_199_p3;
wire   [34:0] x_fu_205_p2;
wire   [9:0] tmp_2_fu_215_p4;
wire   [34:0] x_1_fu_210_p2;
wire   [9:0] tmp_4_fu_230_p4;
wire  signed [15:0] add_ln51_fu_245_p0;
wire  signed [15:0] add_ln51_fu_245_p1;
wire   [15:0] add_ln51_fu_245_p2;
wire   [7:0] tmp_1_fu_251_p4;
wire  signed [9:0] sext_ln232_fu_261_p1;
wire   [25:0] mul_ln241_fu_127_p2;
wire   [25:0] mul_ln241_1_fu_128_p2;
wire   [15:0] trunc_ln241_1_fu_293_p4;
wire   [15:0] trunc_ln2_fu_279_p4;
wire    ap_CS_fsm_state7;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg = 1'b0;
end

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_2u_softmax_config9_s_invert_tahbi #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0_local),
    .q0(invert_table_q0)
);

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_2u_softmax_config9_s_exp_tableibs #(
    .DataWidth( 16 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .we0(exp_table_we0),
    .d0(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_d0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1_local),
    .q1(exp_table_q1)
);

myproject_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start),
    .ap_done(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_done),
    .ap_idle(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_idle),
    .ap_ready(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_ready),
    .table_out_address0(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_address0),
    .table_out_ce0(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_ce0),
    .table_out_we0(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_we0),
    .table_out_d0(grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_d0)
);

myproject_mul_18s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_18s_16s_26_1_1_U457(
    .din0(mul_ln241_fu_127_p0),
    .din1(a_reg_339),
    .dout(mul_ln241_fu_127_p2)
);

myproject_mul_18s_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_18s_16s_26_1_1_U458(
    .din0(mul_ln241_1_fu_128_p0),
    .din1(b_reg_344),
    .dout(mul_ln241_1_fu_128_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_ready == 1'b1)) begin
            grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        a_reg_339 <= exp_table_q1;
        b_reg_344 <= exp_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln66_reg_312 <= icmp_ln66_fu_174_p2;
        tmp_reg_323 <= {{layer8_out_dout[70:36]}};
        trunc_ln66_reg_317 <= trunc_ln66_fu_180_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        inv_exp_sum_reg_354 <= invert_table_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer8_out_empty_n == 1'b0) | (grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((layer9_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_address0 = grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_address0;
    end else begin
        exp_table_address0 = zext_ln223_1_fu_240_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_ce0 = grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_ce0;
    end else begin
        exp_table_ce0 = exp_table_ce0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce0_local = 1'b1;
    end else begin
        exp_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce1_local = 1'b1;
    end else begin
        exp_table_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        exp_table_we0 = grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_table_out_we0;
    end else begin
        exp_table_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        invert_table_ce0_local = 1'b1;
    end else begin
        invert_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer8_out_blk_n = layer8_out_empty_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer8_out_empty_n == 1'b0) | (grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        layer8_out_read = 1'b1;
    end else begin
        layer8_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        layer9_out_TDATA_blk_n = layer9_out_TREADY;
    end else begin
        layer9_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer9_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        layer9_out_TVALID = 1'b1;
    end else begin
        layer9_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((layer8_out_empty_n == 1'b0) | (grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((layer9_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_245_p0 = exp_table_q0;

assign add_ln51_fu_245_p1 = exp_table_q1;

assign add_ln51_fu_245_p2 = ($signed(add_ln51_fu_245_p0) + $signed(add_ln51_fu_245_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign exp_table_address1 = zext_ln223_fu_225_p1;

assign grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start = grp_init_exp_table_ap_ufixed_35_15_5_3_0_softmax_config9_s_fu_154_ap_start_reg;

assign icmp_ln66_fu_174_p2 = (($signed(trunc_ln198_fu_160_p1) < $signed(trunc_ln198_1_fu_164_p4)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln232_fu_265_p1;

assign layer9_out_TDATA = {{trunc_ln241_1_fu_293_p4}, {trunc_ln2_fu_279_p4}};

assign mul_ln241_1_fu_128_p0 = sext_ln241_fu_270_p1;

assign mul_ln241_fu_127_p0 = sext_ln241_fu_270_p1;

assign select_ln66_fu_199_p3 = ((xor_ln66_fu_194_p2[0:0] == 1'b1) ? trunc_ln66_reg_317 : tmp_reg_323);

assign sext_ln232_fu_261_p1 = $signed(tmp_1_fu_251_p4);

assign sext_ln241_fu_270_p1 = $signed(inv_exp_sum_reg_354);

assign tmp_1_fu_251_p4 = {{add_ln51_fu_245_p2[15:8]}};

assign tmp_2_fu_215_p4 = {{x_fu_205_p2[34:25]}};

assign tmp_4_fu_230_p4 = {{x_1_fu_210_p2[34:25]}};

assign trunc_ln198_1_fu_164_p4 = {{layer8_out_dout[71:36]}};

assign trunc_ln198_fu_160_p1 = layer8_out_dout[35:0];

assign trunc_ln241_1_fu_293_p4 = {{mul_ln241_1_fu_128_p2[25:10]}};

assign trunc_ln2_fu_279_p4 = {{mul_ln241_fu_127_p2[25:10]}};

assign trunc_ln66_fu_180_p1 = layer8_out_dout[34:0];

assign x_1_fu_210_p2 = (select_ln66_fu_199_p3 - tmp_reg_323);

assign x_fu_205_p2 = (select_ln66_fu_199_p3 - trunc_ln66_reg_317);

assign xor_ln66_fu_194_p2 = (icmp_ln66_reg_312 ^ 1'd1);

assign zext_ln223_1_fu_240_p1 = tmp_4_fu_230_p4;

assign zext_ln223_fu_225_p1 = tmp_2_fu_215_p4;

assign zext_ln232_fu_265_p1 = $unsigned(sext_ln232_fu_261_p1);

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_2u_softmax_config9_s
