// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer7_out_din,
        layer7_out_full_n,
        layer7_out_write,
        layer7_out_num_data_valid,
        layer7_out_fifo_cap
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [311:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
input  [1:0] layer6_out_num_data_valid;
input  [1:0] layer6_out_fifo_cap;
output  [127:0] layer7_out_din;
input   layer7_out_full_n;
output   layer7_out_write;
input  [1:0] layer7_out_num_data_valid;
input  [1:0] layer7_out_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer6_out_read;
reg layer7_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer6_out_blk_n;
reg    layer7_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [15:0] select_ln51_fu_191_p3;
reg   [15:0] select_ln51_reg_380;
reg    ap_block_state1;
wire   [15:0] select_ln51_1_fu_215_p3;
reg   [15:0] select_ln51_1_reg_385;
wire   [15:0] select_ln51_2_fu_239_p3;
reg   [15:0] select_ln51_2_reg_390;
wire   [15:0] select_ln51_3_fu_263_p3;
reg   [15:0] select_ln51_3_reg_395;
wire   [15:0] select_ln51_4_fu_287_p3;
reg   [15:0] select_ln51_4_reg_400;
wire   [15:0] select_ln51_5_fu_311_p3;
reg   [15:0] select_ln51_5_reg_405;
wire   [15:0] select_ln51_6_fu_335_p3;
reg   [15:0] select_ln51_6_reg_410;
wire   [15:0] select_ln51_7_fu_359_p3;
reg   [15:0] select_ln51_7_reg_415;
wire   [38:0] trunc_ln44_fu_101_p1;
wire   [0:0] icmp_ln51_fu_175_p2;
wire   [15:0] trunc_ln3_fu_181_p4;
wire   [38:0] trunc_ln44_1_fu_105_p4;
wire   [0:0] icmp_ln51_1_fu_199_p2;
wire   [15:0] trunc_ln52_1_fu_205_p4;
wire   [38:0] trunc_ln44_2_fu_115_p4;
wire   [0:0] icmp_ln51_2_fu_223_p2;
wire   [15:0] trunc_ln52_2_fu_229_p4;
wire   [38:0] trunc_ln44_3_fu_125_p4;
wire   [0:0] icmp_ln51_3_fu_247_p2;
wire   [15:0] trunc_ln52_3_fu_253_p4;
wire   [38:0] trunc_ln44_4_fu_135_p4;
wire   [0:0] icmp_ln51_4_fu_271_p2;
wire   [15:0] trunc_ln52_4_fu_277_p4;
wire   [38:0] trunc_ln44_5_fu_145_p4;
wire   [0:0] icmp_ln51_5_fu_295_p2;
wire   [15:0] trunc_ln52_5_fu_301_p4;
wire   [38:0] trunc_ln44_6_fu_155_p4;
wire   [0:0] icmp_ln51_6_fu_319_p2;
wire   [15:0] trunc_ln52_6_fu_325_p4;
wire   [38:0] trunc_ln44_7_fu_165_p4;
wire   [0:0] icmp_ln51_7_fu_343_p2;
wire   [15:0] trunc_ln52_7_fu_349_p4;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer7_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln51_1_reg_385 <= select_ln51_1_fu_215_p3;
        select_ln51_2_reg_390 <= select_ln51_2_fu_239_p3;
        select_ln51_3_reg_395 <= select_ln51_3_fu_263_p3;
        select_ln51_4_reg_400 <= select_ln51_4_fu_287_p3;
        select_ln51_5_reg_405 <= select_ln51_5_fu_311_p3;
        select_ln51_6_reg_410 <= select_ln51_6_fu_335_p3;
        select_ln51_7_reg_415 <= select_ln51_7_fu_359_p3;
        select_ln51_reg_380 <= select_ln51_fu_191_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer7_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer7_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer7_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer7_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer7_out_write = 1'b1;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer7_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer6_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln51_1_fu_199_p2 = (($signed(trunc_ln44_1_fu_105_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_223_p2 = (($signed(trunc_ln44_2_fu_115_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_247_p2 = (($signed(trunc_ln44_3_fu_125_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_271_p2 = (($signed(trunc_ln44_4_fu_135_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_295_p2 = (($signed(trunc_ln44_5_fu_145_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_319_p2 = (($signed(trunc_ln44_6_fu_155_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_343_p2 = (($signed(trunc_ln44_7_fu_165_p4) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_175_p2 = (($signed(trunc_ln44_fu_101_p1) > $signed(39'd0)) ? 1'b1 : 1'b0);

assign layer7_out_din = {{{{{{{{select_ln51_7_reg_415}, {select_ln51_6_reg_410}}, {select_ln51_5_reg_405}}, {select_ln51_4_reg_400}}, {select_ln51_3_reg_395}}, {select_ln51_2_reg_390}}, {select_ln51_1_reg_385}}, {select_ln51_reg_380}};

assign select_ln51_1_fu_215_p3 = ((icmp_ln51_1_fu_199_p2[0:0] == 1'b1) ? trunc_ln52_1_fu_205_p4 : 16'd0);

assign select_ln51_2_fu_239_p3 = ((icmp_ln51_2_fu_223_p2[0:0] == 1'b1) ? trunc_ln52_2_fu_229_p4 : 16'd0);

assign select_ln51_3_fu_263_p3 = ((icmp_ln51_3_fu_247_p2[0:0] == 1'b1) ? trunc_ln52_3_fu_253_p4 : 16'd0);

assign select_ln51_4_fu_287_p3 = ((icmp_ln51_4_fu_271_p2[0:0] == 1'b1) ? trunc_ln52_4_fu_277_p4 : 16'd0);

assign select_ln51_5_fu_311_p3 = ((icmp_ln51_5_fu_295_p2[0:0] == 1'b1) ? trunc_ln52_5_fu_301_p4 : 16'd0);

assign select_ln51_6_fu_335_p3 = ((icmp_ln51_6_fu_319_p2[0:0] == 1'b1) ? trunc_ln52_6_fu_325_p4 : 16'd0);

assign select_ln51_7_fu_359_p3 = ((icmp_ln51_7_fu_343_p2[0:0] == 1'b1) ? trunc_ln52_7_fu_349_p4 : 16'd0);

assign select_ln51_fu_191_p3 = ((icmp_ln51_fu_175_p2[0:0] == 1'b1) ? trunc_ln3_fu_181_p4 : 16'd0);

assign start_out = real_start;

assign trunc_ln3_fu_181_p4 = {{layer6_out_dout[25:10]}};

assign trunc_ln44_1_fu_105_p4 = {{layer6_out_dout[77:39]}};

assign trunc_ln44_2_fu_115_p4 = {{layer6_out_dout[116:78]}};

assign trunc_ln44_3_fu_125_p4 = {{layer6_out_dout[155:117]}};

assign trunc_ln44_4_fu_135_p4 = {{layer6_out_dout[194:156]}};

assign trunc_ln44_5_fu_145_p4 = {{layer6_out_dout[233:195]}};

assign trunc_ln44_6_fu_155_p4 = {{layer6_out_dout[272:234]}};

assign trunc_ln44_7_fu_165_p4 = {{layer6_out_dout[311:273]}};

assign trunc_ln44_fu_101_p1 = layer6_out_dout[38:0];

assign trunc_ln52_1_fu_205_p4 = {{layer6_out_dout[64:49]}};

assign trunc_ln52_2_fu_229_p4 = {{layer6_out_dout[103:88]}};

assign trunc_ln52_3_fu_253_p4 = {{layer6_out_dout[142:127]}};

assign trunc_ln52_4_fu_277_p4 = {{layer6_out_dout[181:166]}};

assign trunc_ln52_5_fu_301_p4 = {{layer6_out_dout[220:205]}};

assign trunc_ln52_6_fu_325_p4 = {{layer6_out_dout[259:244]}};

assign trunc_ln52_7_fu_349_p4 = {{layer6_out_dout[298:283]}};

endmodule //myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config7_s
