// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_val1,
        data_1_val2,
        data_2_val3,
        data_3_val4,
        data_4_val5,
        data_5_val6,
        data_6_val7,
        data_7_val8,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] data_0_val1;
input  [15:0] data_1_val2;
input  [15:0] data_2_val3;
input  [15:0] data_3_val4;
input  [15:0] data_4_val5;
input  [15:0] data_5_val6;
input  [15:0] data_6_val7;
input  [15:0] data_7_val8;
output  [35:0] ap_return_0;
output  [35:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [13:0] trunc_ln_reg_1650;
wire    ap_block_pp0_stage0_11001;
reg   [14:0] trunc_ln42_8_reg_1655;
reg   [15:0] trunc_ln42_10_reg_1660;
reg   [14:0] trunc_ln42_11_reg_1665;
reg   [15:0] trunc_ln42_12_reg_1670;
reg   [15:0] trunc_ln42_13_reg_1675;
wire   [15:0] add_ln58_fu_1513_p2;
reg   [15:0] add_ln58_reg_1680;
wire   [15:0] add_ln58_288_fu_1519_p2;
reg   [15:0] add_ln58_288_reg_1685;
wire   [15:0] add_ln58_295_fu_1525_p2;
reg   [15:0] add_ln58_295_reg_1690;
wire   [15:0] add_ln58_296_fu_1531_p2;
reg   [15:0] add_ln58_296_reg_1695;
wire   [15:0] add_ln58_300_fu_1543_p2;
reg   [15:0] add_ln58_300_reg_1700;
wire  signed [15:0] mul_ln42_9_fu_136_p0;
wire  signed [25:0] sext_ln73_2_fu_1487_p1;
wire   [10:0] mul_ln42_9_fu_136_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] mul_ln73_fu_137_p1;
wire  signed [10:0] mul_ln42_4_fu_138_p1;
wire  signed [15:0] mul_ln42_2_fu_139_p0;
wire  signed [25:0] sext_ln70_120_fu_1349_p1;
wire   [10:0] mul_ln42_2_fu_139_p1;
wire  signed [15:0] mul_ln73_239_fu_140_p0;
wire   [9:0] mul_ln73_239_fu_140_p1;
wire   [8:0] mul_ln73_238_fu_141_p1;
wire  signed [15:0] mul_ln42_3_fu_142_p0;
wire  signed [25:0] sext_ln70_121_fu_1375_p1;
wire   [10:0] mul_ln42_3_fu_142_p1;
wire  signed [15:0] mul_ln42_6_fu_143_p0;
wire  signed [25:0] sext_ln73_1_fu_1431_p1;
wire  signed [10:0] mul_ln42_6_fu_143_p1;
wire  signed [15:0] mul_ln42_1_fu_144_p0;
wire  signed [25:0] sext_ln73_fu_1323_p1;
wire  signed [10:0] mul_ln42_1_fu_144_p1;
wire   [8:0] mul_ln73_241_fu_145_p1;
wire  signed [15:0] mul_ln42_5_fu_146_p0;
wire   [10:0] mul_ln42_5_fu_146_p1;
wire   [8:0] mul_ln73_242_fu_147_p1;
wire  signed [15:0] mul_ln73_240_fu_148_p0;
wire   [9:0] mul_ln73_240_fu_148_p1;
wire  signed [10:0] mul_ln42_7_fu_149_p1;
wire  signed [15:0] mul_ln42_8_fu_150_p0;
wire  signed [10:0] mul_ln42_8_fu_150_p1;
wire  signed [15:0] mul_ln42_fu_151_p0;
wire   [10:0] mul_ln42_fu_151_p1;
wire  signed [15:0] sext_ln70_fu_1289_p0;
wire  signed [15:0] sext_ln70_119_fu_1294_p0;
wire   [23:0] mul_ln73_fu_137_p2;
wire   [24:0] mul_ln73_238_fu_141_p2;
wire   [14:0] trunc_ln42_1_fu_1309_p4;
wire   [25:0] mul_ln42_fu_151_p2;
wire   [25:0] mul_ln42_1_fu_144_p2;
wire   [25:0] mul_ln42_2_fu_139_p2;
wire   [25:0] mul_ln73_239_fu_140_p2;
wire   [25:0] mul_ln42_3_fu_142_p2;
wire   [25:0] mul_ln73_240_fu_148_p2;
wire  signed [15:0] sext_ln42_112_fu_1401_p0;
wire  signed [15:0] sext_ln70_122_fu_1406_p0;
wire   [24:0] mul_ln73_241_fu_145_p2;
wire   [25:0] mul_ln42_4_fu_138_p2;
wire   [25:0] mul_ln42_5_fu_146_p2;
wire   [25:0] mul_ln42_6_fu_143_p2;
wire  signed [15:0] sext_ln42_114_fu_1457_p0;
wire  signed [15:0] sext_ln70_123_fu_1462_p0;
wire   [24:0] mul_ln73_242_fu_147_p2;
wire   [25:0] mul_ln42_7_fu_149_p2;
wire   [25:0] mul_ln42_8_fu_150_p2;
wire   [25:0] mul_ln42_9_fu_136_p2;
wire   [15:0] trunc_ln42_2_fu_1329_p4;
wire   [15:0] trunc_ln42_4_fu_1355_p4;
wire   [15:0] trunc_ln42_6_fu_1381_p4;
wire   [15:0] trunc_ln42_s_fu_1437_p4;
wire   [15:0] trunc_ln42_3_fu_1339_p4;
wire   [15:0] trunc_ln42_5_fu_1365_p4;
wire   [15:0] trunc_ln42_7_fu_1391_p4;
wire   [15:0] trunc_ln42_9_fu_1421_p4;
wire  signed [15:0] sext_ln42_fu_1319_p1;
wire   [15:0] add_ln58_299_fu_1537_p2;
wire   [15:0] trunc_ln42_14_fu_1503_p4;
wire  signed [15:0] sext_ln42_113_fu_1552_p1;
wire  signed [14:0] sext_ln73_3_fu_1549_p1;
wire   [14:0] add_ln58_291_fu_1567_p2;
wire  signed [15:0] sext_ln58_fu_1573_p1;
wire  signed [15:0] sext_ln42_115_fu_1555_p1;
wire   [15:0] add_ln58_292_fu_1577_p2;
wire   [15:0] add_ln58_290_fu_1562_p2;
wire   [15:0] add_ln58_293_fu_1583_p2;
wire   [15:0] add_ln58_289_fu_1558_p2;
wire   [15:0] add_ln58_298_fu_1599_p2;
wire   [15:0] add_ln58_301_fu_1603_p2;
wire   [15:0] add_ln58_297_fu_1595_p2;
wire   [15:0] x_fu_1589_p2;
wire   [25:0] shl_ln_fu_1614_p3;
wire   [15:0] x_10_fu_1608_p2;
wire   [25:0] shl_ln111_8_fu_1626_p3;
wire  signed [35:0] sext_ln110_fu_1622_p1;
wire  signed [35:0] sext_ln18_fu_1634_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U408(
    .din0(mul_ln42_9_fu_136_p0),
    .din1(mul_ln42_9_fu_136_p1),
    .dout(mul_ln42_9_fu_136_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U409(
    .din0(sext_ln70_119_fu_1294_p0),
    .din1(mul_ln73_fu_137_p1),
    .dout(mul_ln73_fu_137_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U410(
    .din0(sext_ln42_112_fu_1401_p0),
    .din1(mul_ln42_4_fu_138_p1),
    .dout(mul_ln42_4_fu_138_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U411(
    .din0(mul_ln42_2_fu_139_p0),
    .din1(mul_ln42_2_fu_139_p1),
    .dout(mul_ln42_2_fu_139_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U412(
    .din0(mul_ln73_239_fu_140_p0),
    .din1(mul_ln73_239_fu_140_p1),
    .dout(mul_ln73_239_fu_140_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U413(
    .din0(sext_ln70_fu_1289_p0),
    .din1(mul_ln73_238_fu_141_p1),
    .dout(mul_ln73_238_fu_141_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U414(
    .din0(mul_ln42_3_fu_142_p0),
    .din1(mul_ln42_3_fu_142_p1),
    .dout(mul_ln42_3_fu_142_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U415(
    .din0(mul_ln42_6_fu_143_p0),
    .din1(mul_ln42_6_fu_143_p1),
    .dout(mul_ln42_6_fu_143_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U416(
    .din0(mul_ln42_1_fu_144_p0),
    .din1(mul_ln42_1_fu_144_p1),
    .dout(mul_ln42_1_fu_144_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U417(
    .din0(sext_ln70_122_fu_1406_p0),
    .din1(mul_ln73_241_fu_145_p1),
    .dout(mul_ln73_241_fu_145_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U418(
    .din0(mul_ln42_5_fu_146_p0),
    .din1(mul_ln42_5_fu_146_p1),
    .dout(mul_ln42_5_fu_146_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U419(
    .din0(sext_ln70_123_fu_1462_p0),
    .din1(mul_ln73_242_fu_147_p1),
    .dout(mul_ln73_242_fu_147_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U420(
    .din0(mul_ln73_240_fu_148_p0),
    .din1(mul_ln73_240_fu_148_p1),
    .dout(mul_ln73_240_fu_148_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U421(
    .din0(sext_ln42_114_fu_1457_p0),
    .din1(mul_ln42_7_fu_149_p1),
    .dout(mul_ln42_7_fu_149_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U422(
    .din0(mul_ln42_8_fu_150_p0),
    .din1(mul_ln42_8_fu_150_p1),
    .dout(mul_ln42_8_fu_150_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U423(
    .din0(mul_ln42_fu_151_p0),
    .din1(mul_ln42_fu_151_p1),
    .dout(mul_ln42_fu_151_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_288_reg_1685 <= add_ln58_288_fu_1519_p2;
        add_ln58_295_reg_1690 <= add_ln58_295_fu_1525_p2;
        add_ln58_296_reg_1695 <= add_ln58_296_fu_1531_p2;
        add_ln58_300_reg_1700 <= add_ln58_300_fu_1543_p2;
        add_ln58_reg_1680 <= add_ln58_fu_1513_p2;
        trunc_ln42_10_reg_1660 <= {{mul_ln42_6_fu_143_p2[25:10]}};
        trunc_ln42_11_reg_1665 <= {{mul_ln73_242_fu_147_p2[24:10]}};
        trunc_ln42_12_reg_1670 <= {{mul_ln42_7_fu_149_p2[25:10]}};
        trunc_ln42_13_reg_1675 <= {{mul_ln42_8_fu_150_p2[25:10]}};
        trunc_ln42_8_reg_1655 <= {{mul_ln73_241_fu_145_p2[24:10]}};
        trunc_ln_reg_1650 <= {{mul_ln73_fu_137_p2[23:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_288_fu_1519_p2 = (trunc_ln42_6_fu_1381_p4 + trunc_ln42_s_fu_1437_p4);

assign add_ln58_289_fu_1558_p2 = (add_ln58_288_reg_1685 + add_ln58_reg_1680);

assign add_ln58_290_fu_1562_p2 = ($signed(trunc_ln42_13_reg_1675) + $signed(sext_ln42_113_fu_1552_p1));

assign add_ln58_291_fu_1567_p2 = ($signed(sext_ln73_3_fu_1549_p1) + $signed(15'd32760));

assign add_ln58_292_fu_1577_p2 = ($signed(sext_ln58_fu_1573_p1) + $signed(sext_ln42_115_fu_1555_p1));

assign add_ln58_293_fu_1583_p2 = (add_ln58_292_fu_1577_p2 + add_ln58_290_fu_1562_p2);

assign add_ln58_295_fu_1525_p2 = (trunc_ln42_3_fu_1339_p4 + trunc_ln42_5_fu_1365_p4);

assign add_ln58_296_fu_1531_p2 = (trunc_ln42_7_fu_1391_p4 + trunc_ln42_9_fu_1421_p4);

assign add_ln58_297_fu_1595_p2 = (add_ln58_296_reg_1695 + add_ln58_295_reg_1690);

assign add_ln58_298_fu_1599_p2 = (trunc_ln42_10_reg_1660 + trunc_ln42_12_reg_1670);

assign add_ln58_299_fu_1537_p2 = ($signed(sext_ln42_fu_1319_p1) + $signed(16'd7));

assign add_ln58_300_fu_1543_p2 = (add_ln58_299_fu_1537_p2 + trunc_ln42_14_fu_1503_p4);

assign add_ln58_301_fu_1603_p2 = (add_ln58_300_reg_1700 + add_ln58_298_fu_1599_p2);

assign add_ln58_fu_1513_p2 = (trunc_ln42_2_fu_1329_p4 + trunc_ln42_4_fu_1355_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln110_fu_1622_p1;

assign ap_return_1 = sext_ln18_fu_1634_p1;

assign mul_ln42_1_fu_144_p0 = sext_ln73_fu_1323_p1;

assign mul_ln42_1_fu_144_p1 = 26'd67108097;

assign mul_ln42_2_fu_139_p0 = sext_ln70_120_fu_1349_p1;

assign mul_ln42_2_fu_139_p1 = 26'd548;

assign mul_ln42_3_fu_142_p0 = sext_ln70_121_fu_1375_p1;

assign mul_ln42_3_fu_142_p1 = 26'd700;

assign mul_ln42_4_fu_138_p1 = 26'd67108274;

assign mul_ln42_5_fu_146_p0 = sext_ln73_1_fu_1431_p1;

assign mul_ln42_5_fu_146_p1 = 26'd736;

assign mul_ln42_6_fu_143_p0 = sext_ln73_1_fu_1431_p1;

assign mul_ln42_6_fu_143_p1 = 26'd67108217;

assign mul_ln42_7_fu_149_p1 = 26'd67108246;

assign mul_ln42_8_fu_150_p0 = sext_ln73_2_fu_1487_p1;

assign mul_ln42_8_fu_150_p1 = 26'd67108134;

assign mul_ln42_9_fu_136_p0 = sext_ln73_2_fu_1487_p1;

assign mul_ln42_9_fu_136_p1 = 26'd778;

assign mul_ln42_fu_151_p0 = sext_ln73_fu_1323_p1;

assign mul_ln42_fu_151_p1 = 26'd595;

assign mul_ln73_238_fu_141_p1 = 25'd145;

assign mul_ln73_239_fu_140_p0 = sext_ln70_120_fu_1349_p1;

assign mul_ln73_239_fu_140_p1 = 26'd375;

assign mul_ln73_240_fu_148_p0 = sext_ln70_121_fu_1375_p1;

assign mul_ln73_240_fu_148_p1 = 26'd454;

assign mul_ln73_241_fu_145_p1 = 25'd241;

assign mul_ln73_242_fu_147_p1 = 25'd150;

assign mul_ln73_fu_137_p1 = 24'd81;

assign sext_ln110_fu_1622_p1 = $signed(shl_ln_fu_1614_p3);

assign sext_ln18_fu_1634_p1 = $signed(shl_ln111_8_fu_1626_p3);

assign sext_ln42_112_fu_1401_p0 = data_4_val5;

assign sext_ln42_113_fu_1552_p1 = $signed(trunc_ln42_8_reg_1655);

assign sext_ln42_114_fu_1457_p0 = data_6_val7;

assign sext_ln42_115_fu_1555_p1 = $signed(trunc_ln42_11_reg_1665);

assign sext_ln42_fu_1319_p1 = $signed(trunc_ln42_1_fu_1309_p4);

assign sext_ln58_fu_1573_p1 = $signed(add_ln58_291_fu_1567_p2);

assign sext_ln70_119_fu_1294_p0 = data_0_val1;

assign sext_ln70_120_fu_1349_p1 = $signed(data_2_val3);

assign sext_ln70_121_fu_1375_p1 = $signed(data_3_val4);

assign sext_ln70_122_fu_1406_p0 = data_4_val5;

assign sext_ln70_123_fu_1462_p0 = data_6_val7;

assign sext_ln70_fu_1289_p0 = data_0_val1;

assign sext_ln73_1_fu_1431_p1 = $signed(data_5_val6);

assign sext_ln73_2_fu_1487_p1 = $signed(data_7_val8);

assign sext_ln73_3_fu_1549_p1 = $signed(trunc_ln_reg_1650);

assign sext_ln73_fu_1323_p1 = $signed(data_1_val2);

assign shl_ln111_8_fu_1626_p3 = {{x_10_fu_1608_p2}, {10'd0}};

assign shl_ln_fu_1614_p3 = {{x_fu_1589_p2}, {10'd0}};

assign trunc_ln42_14_fu_1503_p4 = {{mul_ln42_9_fu_136_p2[25:10]}};

assign trunc_ln42_1_fu_1309_p4 = {{mul_ln73_238_fu_141_p2[24:10]}};

assign trunc_ln42_2_fu_1329_p4 = {{mul_ln42_fu_151_p2[25:10]}};

assign trunc_ln42_3_fu_1339_p4 = {{mul_ln42_1_fu_144_p2[25:10]}};

assign trunc_ln42_4_fu_1355_p4 = {{mul_ln42_2_fu_139_p2[25:10]}};

assign trunc_ln42_5_fu_1365_p4 = {{mul_ln73_239_fu_140_p2[25:10]}};

assign trunc_ln42_6_fu_1381_p4 = {{mul_ln42_3_fu_142_p2[25:10]}};

assign trunc_ln42_7_fu_1391_p4 = {{mul_ln73_240_fu_148_p2[25:10]}};

assign trunc_ln42_9_fu_1421_p4 = {{mul_ln42_4_fu_138_p2[25:10]}};

assign trunc_ln42_s_fu_1437_p4 = {{mul_ln42_5_fu_146_p2[25:10]}};

assign x_10_fu_1608_p2 = (add_ln58_301_fu_1603_p2 + add_ln58_297_fu_1595_p2);

assign x_fu_1589_p2 = (add_ln58_293_fu_1583_p2 + add_ln58_289_fu_1558_p2);

endmodule //myproject_dense_latency_wrapper_ap_fixed_ap_fixed_36_16_5_3_0_config8_s
